#!/usr/bin/perl
# make-loader.pl -- Wrap the wrapper into a dynamic loader
# WARNING: if this breaks, which it will, the regexes need to be manipulated
#          since parsing C code with them is a wonderful experience, but better
#          than doing it by hand for the n-th time. Expected breakage is marked
#          with XXX.

use v5.30;
use warnings;
use strict;

my $wrap_lib_h = $ARGV[0];

die "usage: $0 <header>" unless defined $wrap_lib_h;
open my $wrap_fh, '<', $wrap_lib_h
    or die "cannot open $wrap_lib_h: $!";

open my $loader_c_fh, '>', 'oidfed_wrap_loader.gen.c'
    or die "cannot open: oidfed_wrap_loader.gen.c: $!";
open my $loader_h_fh, '>', 'oidfed_wrap_loader.gen.h'
    or die "cannot open: oidfed_wrap_loader.gen.h: $!";

say $loader_c_fh <<"EOF";
// Generated by make-loader.pl on @{[scalar localtime]}
// Change at your own peril.

EOF
say $loader_h_fh <<"EOF";
// Generated by make-loader.pl on @{[scalar localtime]}
// Change at your own peril.

#ifndef OIDFED_WRAP_LOADER_GEN_H
#define OIDFED_WRAP_LOADER_GEN_H

EOF

while ((local $_ = <$wrap_fh>)) {
    next unless /\Aextern ([\w\s*]+) (oidf(?:ed)?\w+)\((.*)\);\Z/;
    my ($ret, $fn, $args) = ($1, $2, $3);

    my $need_return = $ret eq 'void' ? '' : 'return';
    my $need_comma = $args eq 'void' ? '' : ', ';
    $args = '' if $args eq 'void';

    # XXX function pointers will break this
    my @split_args = map { s/\A.*?(\w+)\z/$1/r } split /\s*,\s*/, $args;

    local $" = ", ";
    say $loader_c_fh <<~"EOF";
    static $ret (*OIFFn_$fn)($args) = 0;
    $ret OIFMayLoad_${fn}_request(request_rec* wrap_request_ctx$need_comma$args) { OIDFED_MAYLOAD_REQUEST($need_return, $fn)(@split_args); }
    $ret OIFMayLoad_${fn}_server(server_rec* wrap_server_ctx$need_comma$args) { OIDFED_MAYLOAD_SERVER($need_return, $fn)(@split_args); };
    EOF

    say $loader_h_fh <<~"EOF";
    #define $fn(ctx, ...) _Generic((ctx),       \\
          request_rec*: OIFMayLoad_${fn}_request, \\
          server_rec*: OIFMayLoad_${fn}_server    \\
        )(ctx __VA_OPT__(,) __VA_ARGS__)
    $ret OIFMayLoad_${fn}_request(request_rec* wrap_request_ctx$need_comma$args);
    $ret OIFMayLoad_${fn}_server(server_rec* warp_server_ctx$need_comma$args);
    EOF
}

say $loader_h_fh <<"EOF";
#endif
EOF
