// Generated by make-loader.pl on Tue Feb  3 14:11:25 2026
// Change at your own peril.

#ifndef OIDFED_WRAP_LOADER_GEN_H
#define OIDFED_WRAP_LOADER_GEN_H


#define oidfedCollectedEntityDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedCollectedEntityDestroy_request, \
      server_rec*: OIFMayLoad_oidfedCollectedEntityDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedCollectedEntityDestroy_request(request_rec* wrap_request_ctx, struct oidfed_collected_entity* ce);
void OIFMayLoad_oidfedCollectedEntityDestroy_server(server_rec* warp_server_ctx, struct oidfed_collected_entity* ce);

#define oidfedCollectedEntityEnumerateUi(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedCollectedEntityEnumerateUi_request, \
      server_rec*: OIFMayLoad_oidfedCollectedEntityEnumerateUi_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_collected_entity_ui_enumerator OIFMayLoad_oidfedCollectedEntityEnumerateUi_request(request_rec* wrap_request_ctx, struct oidfed_collected_entity ce);
struct oidfed_collected_entity_ui_enumerator OIFMayLoad_oidfedCollectedEntityEnumerateUi_server(server_rec* warp_server_ctx, struct oidfed_collected_entity ce);

#define oidfedCollectedEntityNextUi(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedCollectedEntityNextUi_request, \
      server_rec*: OIFMayLoad_oidfedCollectedEntityNextUi_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
_Bool OIFMayLoad_oidfedCollectedEntityNextUi_request(request_rec* wrap_request_ctx, struct oidfed_collected_entity_ui_enumerator* enumer);
_Bool OIFMayLoad_oidfedCollectedEntityNextUi_server(server_rec* warp_server_ctx, struct oidfed_collected_entity_ui_enumerator* enumer);

#define oidfedCollectedEntityFinishUi(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedCollectedEntityFinishUi_request, \
      server_rec*: OIFMayLoad_oidfedCollectedEntityFinishUi_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedCollectedEntityFinishUi_request(request_rec* wrap_request_ctx, struct oidfed_collected_entity_ui_enumerator* enumer);
void OIFMayLoad_oidfedCollectedEntityFinishUi_server(server_rec* warp_server_ctx, struct oidfed_collected_entity_ui_enumerator* enumer);

#define oidfedCollectedEntityGetUiValue(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedCollectedEntityGetUiValue_request, \
      server_rec*: OIFMayLoad_oidfedCollectedEntityGetUiValue_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_ui_info OIFMayLoad_oidfedCollectedEntityGetUiValue_request(request_rec* wrap_request_ctx, struct oidfed_collected_entity_ui_enumerator* enumer);
struct oidfed_ui_info OIFMayLoad_oidfedCollectedEntityGetUiValue_server(server_rec* warp_server_ctx, struct oidfed_collected_entity_ui_enumerator* enumer);

#define oidfedEmptyCollectionFilter(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedEmptyCollectionFilter_request, \
      server_rec*: OIFMayLoad_oidfedEmptyCollectionFilter_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_collection_filter OIFMayLoad_oidfedEmptyCollectionFilter_request(request_rec* wrap_request_ctx);
struct oidfed_collection_filter OIFMayLoad_oidfedEmptyCollectionFilter_server(server_rec* warp_server_ctx);

#define oidfedCollectionFilterDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedCollectionFilterDestroy_request, \
      server_rec*: OIFMayLoad_oidfedCollectionFilterDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedCollectionFilterDestroy_request(request_rec* wrap_request_ctx, struct oidfed_collection_filter* cfs);
void OIFMayLoad_oidfedCollectionFilterDestroy_server(server_rec* warp_server_ctx, struct oidfed_collection_filter* cfs);

#define oidfedCollectionFilterAppend(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedCollectionFilterAppend_request, \
      server_rec*: OIFMayLoad_oidfedCollectionFilterAppend_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedCollectionFilterAppend_request(request_rec* wrap_request_ctx, struct oidfed_collection_filter* cfs, uintptr_t filter);
void OIFMayLoad_oidfedCollectionFilterAppend_server(server_rec* warp_server_ctx, struct oidfed_collection_filter* cfs, uintptr_t filter);

#define oidfedEntityCollectionFilterOPSupportsExplicitRegistration(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedEntityCollectionFilterOPSupportsExplicitRegistration_request, \
      server_rec*: OIFMayLoad_oidfedEntityCollectionFilterOPSupportsExplicitRegistration_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPSupportsExplicitRegistration_request(request_rec* wrap_request_ctx, char** taIds, size_t taIdsCount);
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPSupportsExplicitRegistration_server(server_rec* warp_server_ctx, char** taIds, size_t taIdsCount);

#define oidfedEntityCollectionFilterOPSupportsAutomaticRegistration(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedEntityCollectionFilterOPSupportsAutomaticRegistration_request, \
      server_rec*: OIFMayLoad_oidfedEntityCollectionFilterOPSupportsAutomaticRegistration_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPSupportsAutomaticRegistration_request(request_rec* wrap_request_ctx, char** taIds, size_t taIdsCount);
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPSupportsAutomaticRegistration_server(server_rec* warp_server_ctx, char** taIds, size_t taIdsCount);

#define oidfedEntityCollectionFilterOPSupportedGrantTypesIncludes(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedEntityCollectionFilterOPSupportedGrantTypesIncludes_request, \
      server_rec*: OIFMayLoad_oidfedEntityCollectionFilterOPSupportedGrantTypesIncludes_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPSupportedGrantTypesIncludes_request(request_rec* wrap_request_ctx, char** taIds, size_t taIdsCount, char** grantTypes, size_t grantTypesCount);
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPSupportedGrantTypesIncludes_server(server_rec* warp_server_ctx, char** taIds, size_t taIdsCount, char** grantTypes, size_t grantTypesCount);

#define oidfedEntityCollectionFilterOPSupportedScopesIncludes(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedEntityCollectionFilterOPSupportedScopesIncludes_request, \
      server_rec*: OIFMayLoad_oidfedEntityCollectionFilterOPSupportedScopesIncludes_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPSupportedScopesIncludes_request(request_rec* wrap_request_ctx, char** taIds, size_t taIdsCount, char** scopes, size_t scopesCount);
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPSupportedScopesIncludes_server(server_rec* warp_server_ctx, char** taIds, size_t taIdsCount, char** scopes, size_t scopesCount);

#define oidfedEntityCollectionFilterOPs(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedEntityCollectionFilterOPs_request, \
      server_rec*: OIFMayLoad_oidfedEntityCollectionFilterOPs_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPs_request(request_rec* wrap_request_ctx);
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPs_server(server_rec* warp_server_ctx);

#define oidfedCollectorDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedCollectorDestroy_request, \
      server_rec*: OIFMayLoad_oidfedCollectorDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedCollectorDestroy_request(request_rec* wrap_request_ctx, struct oidfed_collector* collector);
void OIFMayLoad_oidfedCollectorDestroy_server(server_rec* warp_server_ctx, struct oidfed_collector* collector);

#define oidfedCollectorCreateSimple(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedCollectorCreateSimple_request, \
      server_rec*: OIFMayLoad_oidfedCollectorCreateSimple_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_collector OIFMayLoad_oidfedCollectorCreateSimple_request(request_rec* wrap_request_ctx);
struct oidfed_collector OIFMayLoad_oidfedCollectorCreateSimple_server(server_rec* warp_server_ctx);

#define oidfedCollectorCreateSmart(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedCollectorCreateSmart_request, \
      server_rec*: OIFMayLoad_oidfedCollectorCreateSmart_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_collector OIFMayLoad_oidfedCollectorCreateSmart_request(request_rec* wrap_request_ctx, struct oidfed_trust_anchor* anchors, size_t anchorsCount);
struct oidfed_collector OIFMayLoad_oidfedCollectorCreateSmart_server(server_rec* warp_server_ctx, struct oidfed_trust_anchor* anchors, size_t anchorsCount);

#define oidfedCollectorCollectVerifiedEntities(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedCollectorCollectVerifiedEntities_request, \
      server_rec*: OIFMayLoad_oidfedCollectorCollectVerifiedEntities_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
int OIFMayLoad_oidfedCollectorCollectVerifiedEntities_request(request_rec* wrap_request_ctx, struct oidfed_trust_anchor ta, struct oidfed_collector* collector, struct oidfed_collected_entity** entities, size_t* entitiesCount);
int OIFMayLoad_oidfedCollectorCollectVerifiedEntities_server(server_rec* warp_server_ctx, struct oidfed_trust_anchor ta, struct oidfed_collector* collector, struct oidfed_collected_entity** entities, size_t* entitiesCount);

#define oidfedCollectorCollectVerifiedEntitiesWithFilter(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedCollectorCollectVerifiedEntitiesWithFilter_request, \
      server_rec*: OIFMayLoad_oidfedCollectorCollectVerifiedEntitiesWithFilter_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
int OIFMayLoad_oidfedCollectorCollectVerifiedEntitiesWithFilter_request(request_rec* wrap_request_ctx, struct oidfed_trust_anchor ta, struct oidfed_collector* collector, struct oidfed_collection_filter filters, struct oidfed_collected_entity** entities, size_t* entitiesCount);
int OIFMayLoad_oidfedCollectorCollectVerifiedEntitiesWithFilter_server(server_rec* warp_server_ctx, struct oidfed_trust_anchor ta, struct oidfed_collector* collector, struct oidfed_collection_filter filters, struct oidfed_collected_entity** entities, size_t* entitiesCount);

#define oidfedEntityStatementParse(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedEntityStatementParse_request, \
      server_rec*: OIFMayLoad_oidfedEntityStatementParse_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_entity_statement OIFMayLoad_oidfedEntityStatementParse_request(request_rec* wrap_request_ctx, char* jwt, size_t jwtLen, int* errc);
struct oidfed_entity_statement OIFMayLoad_oidfedEntityStatementParse_server(server_rec* warp_server_ctx, char* jwt, size_t jwtLen, int* errc);

#define oidfedEntityStatementDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedEntityStatementDestroy_request, \
      server_rec*: OIFMayLoad_oidfedEntityStatementDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedEntityStatementDestroy_request(request_rec* wrap_request_ctx, struct oidfed_entity_statement* stmt);
void OIFMayLoad_oidfedEntityStatementDestroy_server(server_rec* warp_server_ctx, struct oidfed_entity_statement* stmt);

#define oidfedGetEntityConfiguration(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedGetEntityConfiguration_request, \
      server_rec*: OIFMayLoad_oidfedGetEntityConfiguration_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_entity_statement OIFMayLoad_oidfedGetEntityConfiguration_request(request_rec* wrap_request_ctx, char* entityID, int* errc);
struct oidfed_entity_statement OIFMayLoad_oidfedGetEntityConfiguration_server(server_rec* warp_server_ctx, char* entityID, int* errc);

#define oidfedFederationEntityMetadataCreate(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataCreate_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataCreate_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_federation_entity_metadata OIFMayLoad_oidfedFederationEntityMetadataCreate_request(request_rec* wrap_request_ctx);
struct oidfed_federation_entity_metadata OIFMayLoad_oidfedFederationEntityMetadataCreate_server(server_rec* warp_server_ctx);

#define oidfedFederationEntityMetadataGetFederationFetchEndpoint(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetFederationFetchEndpoint_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetFederationFetchEndpoint_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationFetchEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m);
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationFetchEndpoint_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m);

#define oidfedFederationEntityMetadataSetFederationFetchEndpoint(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetFederationFetchEndpoint_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetFederationFetchEndpoint_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationFetchEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* endpoint);
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationFetchEndpoint_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m, char* endpoint);

#define oidfedFederationEntityMetadataGetFederationListEndpoint(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetFederationListEndpoint_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetFederationListEndpoint_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationListEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m);
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationListEndpoint_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m);

#define oidfedFederationEntityMetadataSetFederationListEndpoint(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetFederationListEndpoint_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetFederationListEndpoint_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationListEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* endpoint);
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationListEndpoint_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m, char* endpoint);

#define oidfedFederationEntityMetadataGetFederationResolveEndpoint(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetFederationResolveEndpoint_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetFederationResolveEndpoint_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationResolveEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m);
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationResolveEndpoint_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m);

#define oidfedFederationEntityMetadataSetFederationResolveEndpoint(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetFederationResolveEndpoint_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetFederationResolveEndpoint_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationResolveEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* endpoint);
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationResolveEndpoint_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m, char* endpoint);

#define oidfedFederationEntityMetadataGetFederationTrustMarkStatusEndpoint(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkStatusEndpoint_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkStatusEndpoint_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkStatusEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m);
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkStatusEndpoint_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m);

#define oidfedFederationEntityMetadataSetFederationTrustMarkStatusEndpoint(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkStatusEndpoint_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkStatusEndpoint_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkStatusEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* endpoint);
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkStatusEndpoint_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m, char* endpoint);

#define oidfedFederationEntityMetadataGetFederationTrustMarkListEndpoint(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkListEndpoint_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkListEndpoint_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkListEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m);
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkListEndpoint_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m);

#define oidfedFederationEntityMetadataSetFederationTrustMarkListEndpoint(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkListEndpoint_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkListEndpoint_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkListEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* endpoint);
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkListEndpoint_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m, char* endpoint);

#define oidfedFederationEntityMetadataGetFederationTrustMarkEndpoint(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkEndpoint_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkEndpoint_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m);
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkEndpoint_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m);

#define oidfedFederationEntityMetadataSetFederationTrustMarkEndpoint(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkEndpoint_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkEndpoint_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* endpoint);
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkEndpoint_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m, char* endpoint);

#define oidfedFederationEntityMetadataGetFederationHistoricalKeysEndpoint(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetFederationHistoricalKeysEndpoint_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetFederationHistoricalKeysEndpoint_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationHistoricalKeysEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m);
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationHistoricalKeysEndpoint_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m);

#define oidfedFederationEntityMetadataSetFederationHistoricalKeysEndpoint(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetFederationHistoricalKeysEndpoint_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetFederationHistoricalKeysEndpoint_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationHistoricalKeysEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* endpoint);
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationHistoricalKeysEndpoint_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m, char* endpoint);

#define oidfedFederationEntityMetadataGetLogoURI(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetLogoURI_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetLogoURI_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedFederationEntityMetadataGetLogoURI_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m);
char* OIFMayLoad_oidfedFederationEntityMetadataGetLogoURI_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m);

#define oidfedFederationEntityMetadataSetLogoURI(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetLogoURI_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetLogoURI_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedFederationEntityMetadataSetLogoURI_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* logoURI);
void OIFMayLoad_oidfedFederationEntityMetadataSetLogoURI_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m, char* logoURI);

#define oidfedFederationEntityMetadataGetPolicyURI(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetPolicyURI_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetPolicyURI_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedFederationEntityMetadataGetPolicyURI_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m);
char* OIFMayLoad_oidfedFederationEntityMetadataGetPolicyURI_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m);

#define oidfedFederationEntityMetadataSetPolicyURI(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetPolicyURI_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetPolicyURI_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedFederationEntityMetadataSetPolicyURI_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* policyURI);
void OIFMayLoad_oidfedFederationEntityMetadataSetPolicyURI_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m, char* policyURI);

#define oidfedFederationEntityMetadataGetInformationURI(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetInformationURI_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetInformationURI_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedFederationEntityMetadataGetInformationURI_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m);
char* OIFMayLoad_oidfedFederationEntityMetadataGetInformationURI_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m);

#define oidfedFederationEntityMetadataSetInformationURI(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetInformationURI_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetInformationURI_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedFederationEntityMetadataSetInformationURI_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* informationURI);
void OIFMayLoad_oidfedFederationEntityMetadataSetInformationURI_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m, char* informationURI);

#define oidfedFederationEntityMetadataGetOrganizationName(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetOrganizationName_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetOrganizationName_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedFederationEntityMetadataGetOrganizationName_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m);
char* OIFMayLoad_oidfedFederationEntityMetadataGetOrganizationName_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m);

#define oidfedFederationEntityMetadataSetOrganizationName(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetOrganizationName_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetOrganizationName_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedFederationEntityMetadataSetOrganizationName_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* organizationName);
void OIFMayLoad_oidfedFederationEntityMetadataSetOrganizationName_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m, char* organizationName);

#define oidfedFederationEntityMetadataGetOrganizationURL(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetOrganizationURL_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataGetOrganizationURL_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedFederationEntityMetadataGetOrganizationURL_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m);
char* OIFMayLoad_oidfedFederationEntityMetadataGetOrganizationURL_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m);

#define oidfedFederationEntityMetadataSetOrganizationURL(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetOrganizationURL_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataSetOrganizationURL_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedFederationEntityMetadataSetOrganizationURL_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* organizationURL);
void OIFMayLoad_oidfedFederationEntityMetadataSetOrganizationURL_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata m, char* organizationURL);

#define oidfedFederationEntityMetadataDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationEntityMetadataDestroy_request, \
      server_rec*: OIFMayLoad_oidfedFederationEntityMetadataDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedFederationEntityMetadataDestroy_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata* m);
void OIFMayLoad_oidfedFederationEntityMetadataDestroy_server(server_rec* warp_server_ctx, struct oidfed_federation_entity_metadata* m);

#define oidfedFederationLeafCreate(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationLeafCreate_request, \
      server_rec*: OIFMayLoad_oidfedFederationLeafCreate_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_federation_leaf OIFMayLoad_oidfedFederationLeafCreate_request(request_rec* wrap_request_ctx, char* entityID, char** authorityHints, size_t authorityHintsCount, struct oidfed_trust_anchor* trustAnchors, size_t trustAnchorsCount, struct oidfed_versatile_signer federationSigner, struct oidfed_versatile_signer oidcSigner, struct oidfed_metadata metadata, int* errc);
struct oidfed_federation_leaf OIFMayLoad_oidfedFederationLeafCreate_server(server_rec* warp_server_ctx, char* entityID, char** authorityHints, size_t authorityHintsCount, struct oidfed_trust_anchor* trustAnchors, size_t trustAnchorsCount, struct oidfed_versatile_signer federationSigner, struct oidfed_versatile_signer oidcSigner, struct oidfed_metadata metadata, int* errc);

#define oidfedFederationLeafDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationLeafDestroy_request, \
      server_rec*: OIFMayLoad_oidfedFederationLeafDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedFederationLeafDestroy_request(request_rec* wrap_request_ctx, struct oidfed_federation_leaf* leaf);
void OIFMayLoad_oidfedFederationLeafDestroy_server(server_rec* warp_server_ctx, struct oidfed_federation_leaf* leaf);

#define oidfedFederationLeafGetAsJWT(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationLeafGetAsJWT_request, \
      server_rec*: OIFMayLoad_oidfedFederationLeafGetAsJWT_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
int OIFMayLoad_oidfedFederationLeafGetAsJWT_request(request_rec* wrap_request_ctx, struct oidfed_federation_leaf leaf, char** bytes, size_t* bytesCount);
int OIFMayLoad_oidfedFederationLeafGetAsJWT_server(server_rec* warp_server_ctx, struct oidfed_federation_leaf leaf, char** bytes, size_t* bytesCount);

#define oidfedFederationLeafGetRequestObjectProducer(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedFederationLeafGetRequestObjectProducer_request, \
      server_rec*: OIFMayLoad_oidfedFederationLeafGetRequestObjectProducer_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_request_producer OIFMayLoad_oidfedFederationLeafGetRequestObjectProducer_request(request_rec* wrap_request_ctx, struct oidfed_federation_leaf leaf);
struct oidfed_request_producer OIFMayLoad_oidfedFederationLeafGetRequestObjectProducer_server(server_rec* warp_server_ctx, struct oidfed_federation_leaf leaf);

#define oidfCreateMap(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfCreateMap_request, \
      server_rec*: OIFMayLoad_oidfCreateMap_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_map OIFMayLoad_oidfCreateMap_request(request_rec* wrap_request_ctx);
struct oidfed_map OIFMayLoad_oidfCreateMap_server(server_rec* warp_server_ctx);

#define oidfMapHasKey(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfMapHasKey_request, \
      server_rec*: OIFMayLoad_oidfMapHasKey_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
_Bool OIFMayLoad_oidfMapHasKey_request(request_rec* wrap_request_ctx, struct oidfed_map m, char* key);
_Bool OIFMayLoad_oidfMapHasKey_server(server_rec* warp_server_ctx, struct oidfed_map m, char* key);

#define oidfMapSetString(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfMapSetString_request, \
      server_rec*: OIFMayLoad_oidfMapSetString_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfMapSetString_request(request_rec* wrap_request_ctx, struct oidfed_map m, char* key, char* value);
void OIFMayLoad_oidfMapSetString_server(server_rec* warp_server_ctx, struct oidfed_map m, char* key, char* value);

#define oidfMapSetInt64(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfMapSetInt64_request, \
      server_rec*: OIFMayLoad_oidfMapSetInt64_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfMapSetInt64_request(request_rec* wrap_request_ctx, struct oidfed_map m, char* key, int64_t value);
void OIFMayLoad_oidfMapSetInt64_server(server_rec* warp_server_ctx, struct oidfed_map m, char* key, int64_t value);

#define oidfedMetadataCreate(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedMetadataCreate_request, \
      server_rec*: OIFMayLoad_oidfedMetadataCreate_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_metadata OIFMayLoad_oidfedMetadataCreate_request(request_rec* wrap_request_ctx);
struct oidfed_metadata OIFMayLoad_oidfedMetadataCreate_server(server_rec* warp_server_ctx);

#define oidfedMetadataGetOPMetadata(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedMetadataGetOPMetadata_request, \
      server_rec*: OIFMayLoad_oidfedMetadataGetOPMetadata_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
uintptr_t OIFMayLoad_oidfedMetadataGetOPMetadata_request(request_rec* wrap_request_ctx, struct oidfed_metadata m);
uintptr_t OIFMayLoad_oidfedMetadataGetOPMetadata_server(server_rec* warp_server_ctx, struct oidfed_metadata m);

#define oidfedMetadataSetOPMetadata(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedMetadataSetOPMetadata_request, \
      server_rec*: OIFMayLoad_oidfedMetadataSetOPMetadata_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedMetadataSetOPMetadata_request(request_rec* wrap_request_ctx, struct oidfed_metadata m, uintptr_t op);
void OIFMayLoad_oidfedMetadataSetOPMetadata_server(server_rec* warp_server_ctx, struct oidfed_metadata m, uintptr_t op);

#define oidfedMetadataGetRPMetadata(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedMetadataGetRPMetadata_request, \
      server_rec*: OIFMayLoad_oidfedMetadataGetRPMetadata_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
uintptr_t OIFMayLoad_oidfedMetadataGetRPMetadata_request(request_rec* wrap_request_ctx, struct oidfed_metadata m);
uintptr_t OIFMayLoad_oidfedMetadataGetRPMetadata_server(server_rec* warp_server_ctx, struct oidfed_metadata m);

#define oidfedMetadataSetRPMetadata(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedMetadataSetRPMetadata_request, \
      server_rec*: OIFMayLoad_oidfedMetadataSetRPMetadata_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedMetadataSetRPMetadata_request(request_rec* wrap_request_ctx, struct oidfed_metadata m, uintptr_t rp);
void OIFMayLoad_oidfedMetadataSetRPMetadata_server(server_rec* warp_server_ctx, struct oidfed_metadata m, uintptr_t rp);

#define oidfedMetadataGetFederationEntityMetadata(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedMetadataGetFederationEntityMetadata_request, \
      server_rec*: OIFMayLoad_oidfedMetadataGetFederationEntityMetadata_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
uintptr_t OIFMayLoad_oidfedMetadataGetFederationEntityMetadata_request(request_rec* wrap_request_ctx, struct oidfed_metadata m);
uintptr_t OIFMayLoad_oidfedMetadataGetFederationEntityMetadata_server(server_rec* warp_server_ctx, struct oidfed_metadata m);

#define oidfedMetadataSetFederationEntityMetadata(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedMetadataSetFederationEntityMetadata_request, \
      server_rec*: OIFMayLoad_oidfedMetadataSetFederationEntityMetadata_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedMetadataSetFederationEntityMetadata_request(request_rec* wrap_request_ctx, struct oidfed_metadata m, uintptr_t fe);
void OIFMayLoad_oidfedMetadataSetFederationEntityMetadata_server(server_rec* warp_server_ctx, struct oidfed_metadata m, uintptr_t fe);

#define oidfedOpenIDRelyingPartyMetadataCreate(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataCreate_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataCreate_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_openid_relying_party_metadata OIFMayLoad_oidfedOpenIDRelyingPartyMetadataCreate_request(request_rec* wrap_request_ctx);
struct oidfed_openid_relying_party_metadata OIFMayLoad_oidfedOpenIDRelyingPartyMetadataCreate_server(server_rec* warp_server_ctx);

#define oidfedOpenIDRelyingPartyMetadataGetClientID(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetClientID_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetClientID_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetClientID_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp);
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetClientID_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp);

#define oidfedOpenIDRelyingPartyMetadataSetClientID(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientID_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientID_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientID_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char* clientID);
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientID_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp, char* clientID);

#define oidfedOpenIDRelyingPartyMetadataGetClientName(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetClientName_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetClientName_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetClientName_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp);
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetClientName_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp);

#define oidfedOpenIDRelyingPartyMetadataSetClientName(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientName_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientName_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientName_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char* clientName);
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientName_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp, char* clientName);

#define oidfedOpenIDRelyingPartyMetadataSetRedirectUris(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetRedirectUris_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetRedirectUris_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetRedirectUris_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char** uris, size_t count);
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetRedirectUris_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp, char** uris, size_t count);

#define oidfedOpenIDRelyingPartyMetadataSetResponseTypes(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetResponseTypes_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetResponseTypes_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetResponseTypes_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char** types, size_t count);
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetResponseTypes_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp, char** types, size_t count);

#define oidfedOpenIDRelyingPartyMetadataSetGrantTypes(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetGrantTypes_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetGrantTypes_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetGrantTypes_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char** types, size_t count);
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetGrantTypes_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp, char** types, size_t count);

#define oidfedOpenIDRelyingPartyMetadataGetApplicationType(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetApplicationType_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetApplicationType_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetApplicationType_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp);
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetApplicationType_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp);

#define oidfedOpenIDRelyingPartyMetadataSetApplicationType(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetApplicationType_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetApplicationType_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetApplicationType_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char* applicationType);
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetApplicationType_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp, char* applicationType);

#define oidfedOpenIDRelyingPartyMetadataGetLogoURI(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetLogoURI_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetLogoURI_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetLogoURI_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp);
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetLogoURI_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp);

#define oidfedOpenIDRelyingPartyMetadataSetLogoURI(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetLogoURI_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetLogoURI_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetLogoURI_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char* logoURI);
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetLogoURI_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp, char* logoURI);

#define oidfedOpenIDRelyingPartyMetadataGetJWKS(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetJWKS_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetJWKS_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
uintptr_t OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetJWKS_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp);
uintptr_t OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetJWKS_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp);

#define oidfedOpenIDRelyingPartyMetadataSetJWKS(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetJWKS_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetJWKS_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetJWKS_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, uintptr_t jwks);
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetJWKS_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp, uintptr_t jwks);

#define oidfedOpenIDRelyingPartyMetadataSetJWKSFromKeyStorage(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetJWKSFromKeyStorage_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetJWKSFromKeyStorage_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetJWKSFromKeyStorage_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, struct oidfed_single_key_storage storage);
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetJWKSFromKeyStorage_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp, struct oidfed_single_key_storage storage);

#define oidfedOpenIDRelyingPartyMetadataGetOrganizationName(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetOrganizationName_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetOrganizationName_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetOrganizationName_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp);
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetOrganizationName_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp);

#define oidfedOpenIDRelyingPartyMetadataSetOrganizationName(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetOrganizationName_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetOrganizationName_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetOrganizationName_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char* organizationName);
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetOrganizationName_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp, char* organizationName);

#define oidfedOpenIDRelyingPartyMetadataSetClientRegistrationTypes(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientRegistrationTypes_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientRegistrationTypes_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientRegistrationTypes_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char** types, size_t count);
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientRegistrationTypes_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata rp, char** types, size_t count);

#define oidfedOpenIDRelyingPartyMetadataDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataDestroy_request, \
      server_rec*: OIFMayLoad_oidfedOpenIDRelyingPartyMetadataDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataDestroy_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata* rp);
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataDestroy_server(server_rec* warp_server_ctx, struct oidfed_openid_relying_party_metadata* rp);

#define oidfedRequestProducerCreate(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedRequestProducerCreate_request, \
      server_rec*: OIFMayLoad_oidfedRequestProducerCreate_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_request_producer OIFMayLoad_oidfedRequestProducerCreate_request(request_rec* wrap_request_ctx, char* entityId, int64_t duration, struct oidfed_versatile_signer signer);
struct oidfed_request_producer OIFMayLoad_oidfedRequestProducerCreate_server(server_rec* warp_server_ctx, char* entityId, int64_t duration, struct oidfed_versatile_signer signer);

#define oidfedRequestProducerDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedRequestProducerDestroy_request, \
      server_rec*: OIFMayLoad_oidfedRequestProducerDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedRequestProducerDestroy_request(request_rec* wrap_request_ctx, struct oidfed_request_producer* producer);
void OIFMayLoad_oidfedRequestProducerDestroy_server(server_rec* warp_server_ctx, struct oidfed_request_producer* producer);

#define oidfedRequestProducerProduceObject(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedRequestProducerProduceObject_request, \
      server_rec*: OIFMayLoad_oidfedRequestProducerProduceObject_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_signed_bytes OIFMayLoad_oidfedRequestProducerProduceObject_request(request_rec* wrap_request_ctx, struct oidfed_request_producer producer, struct oidfed_map requestValues, char** algorithms, size_t algorithmsCount, int* errc);
struct oidfed_signed_bytes OIFMayLoad_oidfedRequestProducerProduceObject_server(server_rec* warp_server_ctx, struct oidfed_request_producer producer, struct oidfed_map requestValues, char** algorithms, size_t algorithmsCount, int* errc);

#define oidfedRequestProducerClientAssertion(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedRequestProducerClientAssertion_request, \
      server_rec*: OIFMayLoad_oidfedRequestProducerClientAssertion_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_signed_bytes OIFMayLoad_oidfedRequestProducerClientAssertion_request(request_rec* wrap_request_ctx, struct oidfed_request_producer producer, char* audience, char** algorithms, size_t algorithmsCount, int* errc);
struct oidfed_signed_bytes OIFMayLoad_oidfedRequestProducerClientAssertion_server(server_rec* warp_server_ctx, struct oidfed_request_producer producer, char* audience, char** algorithms, size_t algorithmsCount, int* errc);

#define oidfedSignedBytesDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedSignedBytesDestroy_request, \
      server_rec*: OIFMayLoad_oidfedSignedBytesDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedSignedBytesDestroy_request(request_rec* wrap_request_ctx, struct oidfed_signed_bytes* sb);
void OIFMayLoad_oidfedSignedBytesDestroy_server(server_rec* warp_server_ctx, struct oidfed_signed_bytes* sb);

#define oidfedSignedBytesGetData(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedSignedBytesGetData_request, \
      server_rec*: OIFMayLoad_oidfedSignedBytesGetData_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedSignedBytesGetData_request(request_rec* wrap_request_ctx, struct oidfed_signed_bytes sb, size_t* count);
char* OIFMayLoad_oidfedSignedBytesGetData_server(server_rec* warp_server_ctx, struct oidfed_signed_bytes sb, size_t* count);

#define oidfedSignatureAlgorithmCreateEmpty(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedSignatureAlgorithmCreateEmpty_request, \
      server_rec*: OIFMayLoad_oidfedSignatureAlgorithmCreateEmpty_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_signature_algorithm OIFMayLoad_oidfedSignatureAlgorithmCreateEmpty_request(request_rec* wrap_request_ctx);
struct oidfed_signature_algorithm OIFMayLoad_oidfedSignatureAlgorithmCreateEmpty_server(server_rec* warp_server_ctx);

#define oidfedSignatureAlgorithmDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedSignatureAlgorithmDestroy_request, \
      server_rec*: OIFMayLoad_oidfedSignatureAlgorithmDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedSignatureAlgorithmDestroy_request(request_rec* wrap_request_ctx, struct oidfed_signature_algorithm* sa);
void OIFMayLoad_oidfedSignatureAlgorithmDestroy_server(server_rec* warp_server_ctx, struct oidfed_signature_algorithm* sa);

#define oidfedSignatureAlgorithmGet(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedSignatureAlgorithmGet_request, \
      server_rec*: OIFMayLoad_oidfedSignatureAlgorithmGet_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_signature_algorithm OIFMayLoad_oidfedSignatureAlgorithmGet_request(request_rec* wrap_request_ctx, char* name, _Bool* succ);
struct oidfed_signature_algorithm OIFMayLoad_oidfedSignatureAlgorithmGet_server(server_rec* warp_server_ctx, char* name, _Bool* succ);

#define oidfedSignerCreateFromPEM(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedSignerCreateFromPEM_request, \
      server_rec*: OIFMayLoad_oidfedSignerCreateFromPEM_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_signer OIFMayLoad_oidfedSignerCreateFromPEM_request(request_rec* wrap_request_ctx, char* pemBytes, size_t pemCount, int* errc);
struct oidfed_signer OIFMayLoad_oidfedSignerCreateFromPEM_server(server_rec* warp_server_ctx, char* pemBytes, size_t pemCount, int* errc);

#define oidfedSignerDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedSignerDestroy_request, \
      server_rec*: OIFMayLoad_oidfedSignerDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedSignerDestroy_request(request_rec* wrap_request_ctx, struct oidfed_signer* s);
void OIFMayLoad_oidfedSignerDestroy_server(server_rec* warp_server_ctx, struct oidfed_signer* s);

#define oidfedSingleKeyStorageCreate(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedSingleKeyStorageCreate_request, \
      server_rec*: OIFMayLoad_oidfedSingleKeyStorageCreate_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_single_key_storage OIFMayLoad_oidfedSingleKeyStorageCreate_request(request_rec* wrap_request_ctx, struct oidfed_signer signer, struct oidfed_signature_algorithm alg);
struct oidfed_single_key_storage OIFMayLoad_oidfedSingleKeyStorageCreate_server(server_rec* warp_server_ctx, struct oidfed_signer signer, struct oidfed_signature_algorithm alg);

#define oidfedSingleKeyStorageDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedSingleKeyStorageDestroy_request, \
      server_rec*: OIFMayLoad_oidfedSingleKeyStorageDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedSingleKeyStorageDestroy_request(request_rec* wrap_request_ctx, struct oidfed_single_key_storage* sks);
void OIFMayLoad_oidfedSingleKeyStorageDestroy_server(server_rec* warp_server_ctx, struct oidfed_single_key_storage* sks);

#define oidfedTrustAnchorDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustAnchorDestroy_request, \
      server_rec*: OIFMayLoad_oidfedTrustAnchorDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedTrustAnchorDestroy_request(request_rec* wrap_request_ctx, struct oidfed_trust_anchor* ta);
void OIFMayLoad_oidfedTrustAnchorDestroy_server(server_rec* warp_server_ctx, struct oidfed_trust_anchor* ta);

#define oidfedTrustAnchorCreate(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustAnchorCreate_request, \
      server_rec*: OIFMayLoad_oidfedTrustAnchorCreate_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_trust_anchor OIFMayLoad_oidfedTrustAnchorCreate_request(request_rec* wrap_request_ctx, char* id);
struct oidfed_trust_anchor OIFMayLoad_oidfedTrustAnchorCreate_server(server_rec* warp_server_ctx, char* id);

#define oidfedTrustMarkCreate(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustMarkCreate_request, \
      server_rec*: OIFMayLoad_oidfedTrustMarkCreate_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_trust_mark OIFMayLoad_oidfedTrustMarkCreate_request(request_rec* wrap_request_ctx);
struct oidfed_trust_mark OIFMayLoad_oidfedTrustMarkCreate_server(server_rec* warp_server_ctx);

#define oidfedTrustMarkSetType(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustMarkSetType_request, \
      server_rec*: OIFMayLoad_oidfedTrustMarkSetType_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedTrustMarkSetType_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm, char* typ);
void OIFMayLoad_oidfedTrustMarkSetType_server(server_rec* warp_server_ctx, struct oidfed_trust_mark tm, char* typ);

#define oidfedTrustMarkGetType(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustMarkGetType_request, \
      server_rec*: OIFMayLoad_oidfedTrustMarkGetType_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedTrustMarkGetType_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm);
char* OIFMayLoad_oidfedTrustMarkGetType_server(server_rec* warp_server_ctx, struct oidfed_trust_mark tm);

#define oidfedTrustMarkSetIssuer(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustMarkSetIssuer_request, \
      server_rec*: OIFMayLoad_oidfedTrustMarkSetIssuer_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedTrustMarkSetIssuer_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm, char* issuer);
void OIFMayLoad_oidfedTrustMarkSetIssuer_server(server_rec* warp_server_ctx, struct oidfed_trust_mark tm, char* issuer);

#define oidfedTrustMarkGetIssuer(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustMarkGetIssuer_request, \
      server_rec*: OIFMayLoad_oidfedTrustMarkGetIssuer_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedTrustMarkGetIssuer_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm);
char* OIFMayLoad_oidfedTrustMarkGetIssuer_server(server_rec* warp_server_ctx, struct oidfed_trust_mark tm);

#define oidfedTrustMarkSetSelfIssued(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustMarkSetSelfIssued_request, \
      server_rec*: OIFMayLoad_oidfedTrustMarkSetSelfIssued_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedTrustMarkSetSelfIssued_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm, _Bool selfIssued);
void OIFMayLoad_oidfedTrustMarkSetSelfIssued_server(server_rec* warp_server_ctx, struct oidfed_trust_mark tm, _Bool selfIssued);

#define oidfedTrustMarkIsSelfIssued(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustMarkIsSelfIssued_request, \
      server_rec*: OIFMayLoad_oidfedTrustMarkIsSelfIssued_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
_Bool OIFMayLoad_oidfedTrustMarkIsSelfIssued_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm);
_Bool OIFMayLoad_oidfedTrustMarkIsSelfIssued_server(server_rec* warp_server_ctx, struct oidfed_trust_mark tm);

#define oidfedTrustMarkSetJwt(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustMarkSetJwt_request, \
      server_rec*: OIFMayLoad_oidfedTrustMarkSetJwt_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedTrustMarkSetJwt_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm, char* jwt);
void OIFMayLoad_oidfedTrustMarkSetJwt_server(server_rec* warp_server_ctx, struct oidfed_trust_mark tm, char* jwt);

#define oidfedTrustMarkGetJwt(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustMarkGetJwt_request, \
      server_rec*: OIFMayLoad_oidfedTrustMarkGetJwt_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
char* OIFMayLoad_oidfedTrustMarkGetJwt_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm);
char* OIFMayLoad_oidfedTrustMarkGetJwt_server(server_rec* warp_server_ctx, struct oidfed_trust_mark tm);

#define oidfedTrustMarkSetRefresh(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustMarkSetRefresh_request, \
      server_rec*: OIFMayLoad_oidfedTrustMarkSetRefresh_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedTrustMarkSetRefresh_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm, _Bool refresh);
void OIFMayLoad_oidfedTrustMarkSetRefresh_server(server_rec* warp_server_ctx, struct oidfed_trust_mark tm, _Bool refresh);

#define oidfedTrustMarkIsRefresh(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustMarkIsRefresh_request, \
      server_rec*: OIFMayLoad_oidfedTrustMarkIsRefresh_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
_Bool OIFMayLoad_oidfedTrustMarkIsRefresh_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm);
_Bool OIFMayLoad_oidfedTrustMarkIsRefresh_server(server_rec* warp_server_ctx, struct oidfed_trust_mark tm);

#define oidfedTrustMarkSetMinLifetimeSeconds(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustMarkSetMinLifetimeSeconds_request, \
      server_rec*: OIFMayLoad_oidfedTrustMarkSetMinLifetimeSeconds_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedTrustMarkSetMinLifetimeSeconds_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm, uint64_t minLifetime);
void OIFMayLoad_oidfedTrustMarkSetMinLifetimeSeconds_server(server_rec* warp_server_ctx, struct oidfed_trust_mark tm, uint64_t minLifetime);

#define oidfedTrustMarkGetMinLifetimeSeconds(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustMarkGetMinLifetimeSeconds_request, \
      server_rec*: OIFMayLoad_oidfedTrustMarkGetMinLifetimeSeconds_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
uint64_t OIFMayLoad_oidfedTrustMarkGetMinLifetimeSeconds_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm);
uint64_t OIFMayLoad_oidfedTrustMarkGetMinLifetimeSeconds_server(server_rec* warp_server_ctx, struct oidfed_trust_mark tm);

#define oidfedTrustMarkSetRefreshGracePeriod(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustMarkSetRefreshGracePeriod_request, \
      server_rec*: OIFMayLoad_oidfedTrustMarkSetRefreshGracePeriod_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedTrustMarkSetRefreshGracePeriod_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm, uint64_t refreshGracePeriod);
void OIFMayLoad_oidfedTrustMarkSetRefreshGracePeriod_server(server_rec* warp_server_ctx, struct oidfed_trust_mark tm, uint64_t refreshGracePeriod);

#define oidfedTrustMarkGetRefreshGracePeriod(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustMarkGetRefreshGracePeriod_request, \
      server_rec*: OIFMayLoad_oidfedTrustMarkGetRefreshGracePeriod_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
uint64_t OIFMayLoad_oidfedTrustMarkGetRefreshGracePeriod_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm);
uint64_t OIFMayLoad_oidfedTrustMarkGetRefreshGracePeriod_server(server_rec* warp_server_ctx, struct oidfed_trust_mark tm);

#define oidfedTrustMarkDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustMarkDestroy_request, \
      server_rec*: OIFMayLoad_oidfedTrustMarkDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedTrustMarkDestroy_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark* tm);
void OIFMayLoad_oidfedTrustMarkDestroy_server(server_rec* warp_server_ctx, struct oidfed_trust_mark* tm);

#define oidfedTrustResolverCreate(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustResolverCreate_request, \
      server_rec*: OIFMayLoad_oidfedTrustResolverCreate_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_trust_resolver OIFMayLoad_oidfedTrustResolverCreate_request(request_rec* wrap_request_ctx, char* subID, struct oidfed_trust_anchor* anchors, size_t anchorsCount);
struct oidfed_trust_resolver OIFMayLoad_oidfedTrustResolverCreate_server(server_rec* warp_server_ctx, char* subID, struct oidfed_trust_anchor* anchors, size_t anchorsCount);

#define oidfedTrustResolverDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustResolverDestroy_request, \
      server_rec*: OIFMayLoad_oidfedTrustResolverDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedTrustResolverDestroy_request(request_rec* wrap_request_ctx, struct oidfed_trust_resolver* r);
void OIFMayLoad_oidfedTrustResolverDestroy_server(server_rec* warp_server_ctx, struct oidfed_trust_resolver* r);

#define oidfedTrustResolverResolveToValidChains(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustResolverResolveToValidChains_request, \
      server_rec*: OIFMayLoad_oidfedTrustResolverResolveToValidChains_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_trust_chains OIFMayLoad_oidfedTrustResolverResolveToValidChains_request(request_rec* wrap_request_ctx, struct oidfed_trust_resolver r);
struct oidfed_trust_chains OIFMayLoad_oidfedTrustResolverResolveToValidChains_server(server_rec* warp_server_ctx, struct oidfed_trust_resolver r);

#define oidfedTrustChainsCount(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustChainsCount_request, \
      server_rec*: OIFMayLoad_oidfedTrustChainsCount_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
size_t OIFMayLoad_oidfedTrustChainsCount_request(request_rec* wrap_request_ctx, struct oidfed_trust_chains chains);
size_t OIFMayLoad_oidfedTrustChainsCount_server(server_rec* warp_server_ctx, struct oidfed_trust_chains chains);

#define oidfedTrustChainsGet(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustChainsGet_request, \
      server_rec*: OIFMayLoad_oidfedTrustChainsGet_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_trust_chain OIFMayLoad_oidfedTrustChainsGet_request(request_rec* wrap_request_ctx, struct oidfed_trust_chains chains, size_t index);
struct oidfed_trust_chain OIFMayLoad_oidfedTrustChainsGet_server(server_rec* warp_server_ctx, struct oidfed_trust_chains chains, size_t index);

#define oidfedTrustChainsDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustChainsDestroy_request, \
      server_rec*: OIFMayLoad_oidfedTrustChainsDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedTrustChainsDestroy_request(request_rec* wrap_request_ctx, struct oidfed_trust_chains* chains);
void OIFMayLoad_oidfedTrustChainsDestroy_server(server_rec* warp_server_ctx, struct oidfed_trust_chains* chains);

#define oidfedTrustChainDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustChainDestroy_request, \
      server_rec*: OIFMayLoad_oidfedTrustChainDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedTrustChainDestroy_request(request_rec* wrap_request_ctx, struct oidfed_trust_chain* chain);
void OIFMayLoad_oidfedTrustChainDestroy_server(server_rec* warp_server_ctx, struct oidfed_trust_chain* chain);

#define oidfedTrustChainGetMetadata(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedTrustChainGetMetadata_request, \
      server_rec*: OIFMayLoad_oidfedTrustChainGetMetadata_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
struct oidfed_metadata OIFMayLoad_oidfedTrustChainGetMetadata_request(request_rec* wrap_request_ctx, struct oidfed_trust_chain chain, int* errc);
struct oidfed_metadata OIFMayLoad_oidfedTrustChainGetMetadata_server(server_rec* warp_server_ctx, struct oidfed_trust_chain chain, int* errc);

#define oidfedMetadataDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedMetadataDestroy_request, \
      server_rec*: OIFMayLoad_oidfedMetadataDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedMetadataDestroy_request(request_rec* wrap_request_ctx, struct oidfed_metadata* m);
void OIFMayLoad_oidfedMetadataDestroy_server(server_rec* warp_server_ctx, struct oidfed_metadata* m);

#define oidfedUiInfoDestroy(ctx, ...) _Generic((ctx),       \
      request_rec*: OIFMayLoad_oidfedUiInfoDestroy_request, \
      server_rec*: OIFMayLoad_oidfedUiInfoDestroy_server    \
    )(ctx __VA_OPT__(,) __VA_ARGS__)
void OIFMayLoad_oidfedUiInfoDestroy_request(request_rec* wrap_request_ctx, struct oidfed_ui_info* ui);
void OIFMayLoad_oidfedUiInfoDestroy_server(server_rec* warp_server_ctx, struct oidfed_ui_info* ui);

#endif

