// Generated by make-loader.pl on Wed Mar  4 13:55:07 2026
// Change at your own peril.


static void (*OIFFn_oidfedCollectedEntityDestroy)(struct oidfed_collected_entity* ce) = 0;
void OIFMayLoad_oidfedCollectedEntityDestroy_request(request_rec* wrap_request_ctx, struct oidfed_collected_entity* ce) { OIDFED_MAYLOAD_REQUEST(, oidfedCollectedEntityDestroy)(ce); }
void OIFMayLoad_oidfedCollectedEntityDestroy_server(server_rec* wrap_server_ctx, struct oidfed_collected_entity* ce) { OIDFED_MAYLOAD_SERVER(, oidfedCollectedEntityDestroy)(ce); };

static struct oidfed_collected_entity_ui_enumerator (*OIFFn_oidfedCollectedEntityEnumerateUi)(struct oidfed_collected_entity ce) = 0;
struct oidfed_collected_entity_ui_enumerator OIFMayLoad_oidfedCollectedEntityEnumerateUi_request(request_rec* wrap_request_ctx, struct oidfed_collected_entity ce) { OIDFED_MAYLOAD_REQUEST(return, oidfedCollectedEntityEnumerateUi)(ce); }
struct oidfed_collected_entity_ui_enumerator OIFMayLoad_oidfedCollectedEntityEnumerateUi_server(server_rec* wrap_server_ctx, struct oidfed_collected_entity ce) { OIDFED_MAYLOAD_SERVER(return, oidfedCollectedEntityEnumerateUi)(ce); };

static _Bool (*OIFFn_oidfedCollectedEntityNextUi)(struct oidfed_collected_entity_ui_enumerator* enumer) = 0;
_Bool OIFMayLoad_oidfedCollectedEntityNextUi_request(request_rec* wrap_request_ctx, struct oidfed_collected_entity_ui_enumerator* enumer) { OIDFED_MAYLOAD_REQUEST(return, oidfedCollectedEntityNextUi)(enumer); }
_Bool OIFMayLoad_oidfedCollectedEntityNextUi_server(server_rec* wrap_server_ctx, struct oidfed_collected_entity_ui_enumerator* enumer) { OIDFED_MAYLOAD_SERVER(return, oidfedCollectedEntityNextUi)(enumer); };

static void (*OIFFn_oidfedCollectedEntityFinishUi)(struct oidfed_collected_entity_ui_enumerator* enumer) = 0;
void OIFMayLoad_oidfedCollectedEntityFinishUi_request(request_rec* wrap_request_ctx, struct oidfed_collected_entity_ui_enumerator* enumer) { OIDFED_MAYLOAD_REQUEST(, oidfedCollectedEntityFinishUi)(enumer); }
void OIFMayLoad_oidfedCollectedEntityFinishUi_server(server_rec* wrap_server_ctx, struct oidfed_collected_entity_ui_enumerator* enumer) { OIDFED_MAYLOAD_SERVER(, oidfedCollectedEntityFinishUi)(enumer); };

static struct oidfed_ui_info (*OIFFn_oidfedCollectedEntityGetUiValue)(struct oidfed_collected_entity_ui_enumerator* enumer) = 0;
struct oidfed_ui_info OIFMayLoad_oidfedCollectedEntityGetUiValue_request(request_rec* wrap_request_ctx, struct oidfed_collected_entity_ui_enumerator* enumer) { OIDFED_MAYLOAD_REQUEST(return, oidfedCollectedEntityGetUiValue)(enumer); }
struct oidfed_ui_info OIFMayLoad_oidfedCollectedEntityGetUiValue_server(server_rec* wrap_server_ctx, struct oidfed_collected_entity_ui_enumerator* enumer) { OIDFED_MAYLOAD_SERVER(return, oidfedCollectedEntityGetUiValue)(enumer); };

static struct oidfed_collection_filter (*OIFFn_oidfedEmptyCollectionFilter)() = 0;
struct oidfed_collection_filter OIFMayLoad_oidfedEmptyCollectionFilter_request(request_rec* wrap_request_ctx) { OIDFED_MAYLOAD_REQUEST(return, oidfedEmptyCollectionFilter)(); }
struct oidfed_collection_filter OIFMayLoad_oidfedEmptyCollectionFilter_server(server_rec* wrap_server_ctx) { OIDFED_MAYLOAD_SERVER(return, oidfedEmptyCollectionFilter)(); };

static void (*OIFFn_oidfedCollectionFilterDestroy)(struct oidfed_collection_filter* cfs) = 0;
void OIFMayLoad_oidfedCollectionFilterDestroy_request(request_rec* wrap_request_ctx, struct oidfed_collection_filter* cfs) { OIDFED_MAYLOAD_REQUEST(, oidfedCollectionFilterDestroy)(cfs); }
void OIFMayLoad_oidfedCollectionFilterDestroy_server(server_rec* wrap_server_ctx, struct oidfed_collection_filter* cfs) { OIDFED_MAYLOAD_SERVER(, oidfedCollectionFilterDestroy)(cfs); };

static void (*OIFFn_oidfedCollectionFilterAppend)(struct oidfed_collection_filter* cfs, uintptr_t filter) = 0;
void OIFMayLoad_oidfedCollectionFilterAppend_request(request_rec* wrap_request_ctx, struct oidfed_collection_filter* cfs, uintptr_t filter) { OIDFED_MAYLOAD_REQUEST(, oidfedCollectionFilterAppend)(cfs, filter); }
void OIFMayLoad_oidfedCollectionFilterAppend_server(server_rec* wrap_server_ctx, struct oidfed_collection_filter* cfs, uintptr_t filter) { OIDFED_MAYLOAD_SERVER(, oidfedCollectionFilterAppend)(cfs, filter); };

static uintptr_t (*OIFFn_oidfedEntityCollectionFilterOPSupportsExplicitRegistration)(char** taIds, size_t taIdsCount) = 0;
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPSupportsExplicitRegistration_request(request_rec* wrap_request_ctx, char** taIds, size_t taIdsCount) { OIDFED_MAYLOAD_REQUEST(return, oidfedEntityCollectionFilterOPSupportsExplicitRegistration)(taIds, taIdsCount); }
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPSupportsExplicitRegistration_server(server_rec* wrap_server_ctx, char** taIds, size_t taIdsCount) { OIDFED_MAYLOAD_SERVER(return, oidfedEntityCollectionFilterOPSupportsExplicitRegistration)(taIds, taIdsCount); };

static uintptr_t (*OIFFn_oidfedEntityCollectionFilterOPSupportsAutomaticRegistration)(char** taIds, size_t taIdsCount) = 0;
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPSupportsAutomaticRegistration_request(request_rec* wrap_request_ctx, char** taIds, size_t taIdsCount) { OIDFED_MAYLOAD_REQUEST(return, oidfedEntityCollectionFilterOPSupportsAutomaticRegistration)(taIds, taIdsCount); }
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPSupportsAutomaticRegistration_server(server_rec* wrap_server_ctx, char** taIds, size_t taIdsCount) { OIDFED_MAYLOAD_SERVER(return, oidfedEntityCollectionFilterOPSupportsAutomaticRegistration)(taIds, taIdsCount); };

static uintptr_t (*OIFFn_oidfedEntityCollectionFilterOPSupportedGrantTypesIncludes)(char** taIds, size_t taIdsCount, char** grantTypes, size_t grantTypesCount) = 0;
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPSupportedGrantTypesIncludes_request(request_rec* wrap_request_ctx, char** taIds, size_t taIdsCount, char** grantTypes, size_t grantTypesCount) { OIDFED_MAYLOAD_REQUEST(return, oidfedEntityCollectionFilterOPSupportedGrantTypesIncludes)(taIds, taIdsCount, grantTypes, grantTypesCount); }
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPSupportedGrantTypesIncludes_server(server_rec* wrap_server_ctx, char** taIds, size_t taIdsCount, char** grantTypes, size_t grantTypesCount) { OIDFED_MAYLOAD_SERVER(return, oidfedEntityCollectionFilterOPSupportedGrantTypesIncludes)(taIds, taIdsCount, grantTypes, grantTypesCount); };

static uintptr_t (*OIFFn_oidfedEntityCollectionFilterOPSupportedScopesIncludes)(char** taIds, size_t taIdsCount, char** scopes, size_t scopesCount) = 0;
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPSupportedScopesIncludes_request(request_rec* wrap_request_ctx, char** taIds, size_t taIdsCount, char** scopes, size_t scopesCount) { OIDFED_MAYLOAD_REQUEST(return, oidfedEntityCollectionFilterOPSupportedScopesIncludes)(taIds, taIdsCount, scopes, scopesCount); }
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPSupportedScopesIncludes_server(server_rec* wrap_server_ctx, char** taIds, size_t taIdsCount, char** scopes, size_t scopesCount) { OIDFED_MAYLOAD_SERVER(return, oidfedEntityCollectionFilterOPSupportedScopesIncludes)(taIds, taIdsCount, scopes, scopesCount); };

static uintptr_t (*OIFFn_oidfedEntityCollectionFilterOPs)() = 0;
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPs_request(request_rec* wrap_request_ctx) { OIDFED_MAYLOAD_REQUEST(return, oidfedEntityCollectionFilterOPs)(); }
uintptr_t OIFMayLoad_oidfedEntityCollectionFilterOPs_server(server_rec* wrap_server_ctx) { OIDFED_MAYLOAD_SERVER(return, oidfedEntityCollectionFilterOPs)(); };

static void (*OIFFn_oidfedCollectorDestroy)(struct oidfed_collector* collector) = 0;
void OIFMayLoad_oidfedCollectorDestroy_request(request_rec* wrap_request_ctx, struct oidfed_collector* collector) { OIDFED_MAYLOAD_REQUEST(, oidfedCollectorDestroy)(collector); }
void OIFMayLoad_oidfedCollectorDestroy_server(server_rec* wrap_server_ctx, struct oidfed_collector* collector) { OIDFED_MAYLOAD_SERVER(, oidfedCollectorDestroy)(collector); };

static struct oidfed_collector (*OIFFn_oidfedCollectorCreateSimple)() = 0;
struct oidfed_collector OIFMayLoad_oidfedCollectorCreateSimple_request(request_rec* wrap_request_ctx) { OIDFED_MAYLOAD_REQUEST(return, oidfedCollectorCreateSimple)(); }
struct oidfed_collector OIFMayLoad_oidfedCollectorCreateSimple_server(server_rec* wrap_server_ctx) { OIDFED_MAYLOAD_SERVER(return, oidfedCollectorCreateSimple)(); };

static struct oidfed_collector (*OIFFn_oidfedCollectorCreateSmart)(struct oidfed_trust_anchor* anchors, size_t anchorsCount) = 0;
struct oidfed_collector OIFMayLoad_oidfedCollectorCreateSmart_request(request_rec* wrap_request_ctx, struct oidfed_trust_anchor* anchors, size_t anchorsCount) { OIDFED_MAYLOAD_REQUEST(return, oidfedCollectorCreateSmart)(anchors, anchorsCount); }
struct oidfed_collector OIFMayLoad_oidfedCollectorCreateSmart_server(server_rec* wrap_server_ctx, struct oidfed_trust_anchor* anchors, size_t anchorsCount) { OIDFED_MAYLOAD_SERVER(return, oidfedCollectorCreateSmart)(anchors, anchorsCount); };

static int (*OIFFn_oidfedCollectorCollectVerifiedEntities)(struct oidfed_trust_anchor ta, struct oidfed_collector* collector, struct oidfed_collected_entity** entities, size_t* entitiesCount) = 0;
int OIFMayLoad_oidfedCollectorCollectVerifiedEntities_request(request_rec* wrap_request_ctx, struct oidfed_trust_anchor ta, struct oidfed_collector* collector, struct oidfed_collected_entity** entities, size_t* entitiesCount) { OIDFED_MAYLOAD_REQUEST(return, oidfedCollectorCollectVerifiedEntities)(ta, collector, entities, entitiesCount); }
int OIFMayLoad_oidfedCollectorCollectVerifiedEntities_server(server_rec* wrap_server_ctx, struct oidfed_trust_anchor ta, struct oidfed_collector* collector, struct oidfed_collected_entity** entities, size_t* entitiesCount) { OIDFED_MAYLOAD_SERVER(return, oidfedCollectorCollectVerifiedEntities)(ta, collector, entities, entitiesCount); };

static int (*OIFFn_oidfedCollectorCollectVerifiedEntitiesWithFilter)(struct oidfed_trust_anchor ta, struct oidfed_collector* collector, struct oidfed_collection_filter filters, struct oidfed_collected_entity** entities, size_t* entitiesCount) = 0;
int OIFMayLoad_oidfedCollectorCollectVerifiedEntitiesWithFilter_request(request_rec* wrap_request_ctx, struct oidfed_trust_anchor ta, struct oidfed_collector* collector, struct oidfed_collection_filter filters, struct oidfed_collected_entity** entities, size_t* entitiesCount) { OIDFED_MAYLOAD_REQUEST(return, oidfedCollectorCollectVerifiedEntitiesWithFilter)(ta, collector, filters, entities, entitiesCount); }
int OIFMayLoad_oidfedCollectorCollectVerifiedEntitiesWithFilter_server(server_rec* wrap_server_ctx, struct oidfed_trust_anchor ta, struct oidfed_collector* collector, struct oidfed_collection_filter filters, struct oidfed_collected_entity** entities, size_t* entitiesCount) { OIDFED_MAYLOAD_SERVER(return, oidfedCollectorCollectVerifiedEntitiesWithFilter)(ta, collector, filters, entities, entitiesCount); };

static struct oidfed_entity_statement (*OIFFn_oidfedEntityStatementParse)(char* jwt, size_t jwtLen, int* errc) = 0;
struct oidfed_entity_statement OIFMayLoad_oidfedEntityStatementParse_request(request_rec* wrap_request_ctx, char* jwt, size_t jwtLen, int* errc) { OIDFED_MAYLOAD_REQUEST(return, oidfedEntityStatementParse)(jwt, jwtLen, errc); }
struct oidfed_entity_statement OIFMayLoad_oidfedEntityStatementParse_server(server_rec* wrap_server_ctx, char* jwt, size_t jwtLen, int* errc) { OIDFED_MAYLOAD_SERVER(return, oidfedEntityStatementParse)(jwt, jwtLen, errc); };

static void (*OIFFn_oidfedEntityStatementDestroy)(struct oidfed_entity_statement* stmt) = 0;
void OIFMayLoad_oidfedEntityStatementDestroy_request(request_rec* wrap_request_ctx, struct oidfed_entity_statement* stmt) { OIDFED_MAYLOAD_REQUEST(, oidfedEntityStatementDestroy)(stmt); }
void OIFMayLoad_oidfedEntityStatementDestroy_server(server_rec* wrap_server_ctx, struct oidfed_entity_statement* stmt) { OIDFED_MAYLOAD_SERVER(, oidfedEntityStatementDestroy)(stmt); };

static struct oidfed_entity_statement (*OIFFn_oidfedGetEntityConfiguration)(char* entityID, int* errc) = 0;
struct oidfed_entity_statement OIFMayLoad_oidfedGetEntityConfiguration_request(request_rec* wrap_request_ctx, char* entityID, int* errc) { OIDFED_MAYLOAD_REQUEST(return, oidfedGetEntityConfiguration)(entityID, errc); }
struct oidfed_entity_statement OIFMayLoad_oidfedGetEntityConfiguration_server(server_rec* wrap_server_ctx, char* entityID, int* errc) { OIDFED_MAYLOAD_SERVER(return, oidfedGetEntityConfiguration)(entityID, errc); };

static struct oidfed_federation_entity_metadata (*OIFFn_oidfedFederationEntityMetadataCreate)() = 0;
struct oidfed_federation_entity_metadata OIFMayLoad_oidfedFederationEntityMetadataCreate_request(request_rec* wrap_request_ctx) { OIDFED_MAYLOAD_REQUEST(return, oidfedFederationEntityMetadataCreate)(); }
struct oidfed_federation_entity_metadata OIFMayLoad_oidfedFederationEntityMetadataCreate_server(server_rec* wrap_server_ctx) { OIDFED_MAYLOAD_SERVER(return, oidfedFederationEntityMetadataCreate)(); };

static char* (*OIFFn_oidfedFederationEntityMetadataGetFederationFetchEndpoint)(struct oidfed_federation_entity_metadata m) = 0;
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationFetchEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedFederationEntityMetadataGetFederationFetchEndpoint)(m); }
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationFetchEndpoint_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedFederationEntityMetadataGetFederationFetchEndpoint)(m); };

static void (*OIFFn_oidfedFederationEntityMetadataSetFederationFetchEndpoint)(struct oidfed_federation_entity_metadata m, char* endpoint) = 0;
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationFetchEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* endpoint) { OIDFED_MAYLOAD_REQUEST(, oidfedFederationEntityMetadataSetFederationFetchEndpoint)(m, endpoint); }
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationFetchEndpoint_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m, char* endpoint) { OIDFED_MAYLOAD_SERVER(, oidfedFederationEntityMetadataSetFederationFetchEndpoint)(m, endpoint); };

static char* (*OIFFn_oidfedFederationEntityMetadataGetFederationListEndpoint)(struct oidfed_federation_entity_metadata m) = 0;
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationListEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedFederationEntityMetadataGetFederationListEndpoint)(m); }
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationListEndpoint_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedFederationEntityMetadataGetFederationListEndpoint)(m); };

static void (*OIFFn_oidfedFederationEntityMetadataSetFederationListEndpoint)(struct oidfed_federation_entity_metadata m, char* endpoint) = 0;
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationListEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* endpoint) { OIDFED_MAYLOAD_REQUEST(, oidfedFederationEntityMetadataSetFederationListEndpoint)(m, endpoint); }
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationListEndpoint_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m, char* endpoint) { OIDFED_MAYLOAD_SERVER(, oidfedFederationEntityMetadataSetFederationListEndpoint)(m, endpoint); };

static char* (*OIFFn_oidfedFederationEntityMetadataGetFederationResolveEndpoint)(struct oidfed_federation_entity_metadata m) = 0;
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationResolveEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedFederationEntityMetadataGetFederationResolveEndpoint)(m); }
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationResolveEndpoint_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedFederationEntityMetadataGetFederationResolveEndpoint)(m); };

static void (*OIFFn_oidfedFederationEntityMetadataSetFederationResolveEndpoint)(struct oidfed_federation_entity_metadata m, char* endpoint) = 0;
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationResolveEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* endpoint) { OIDFED_MAYLOAD_REQUEST(, oidfedFederationEntityMetadataSetFederationResolveEndpoint)(m, endpoint); }
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationResolveEndpoint_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m, char* endpoint) { OIDFED_MAYLOAD_SERVER(, oidfedFederationEntityMetadataSetFederationResolveEndpoint)(m, endpoint); };

static char* (*OIFFn_oidfedFederationEntityMetadataGetFederationTrustMarkStatusEndpoint)(struct oidfed_federation_entity_metadata m) = 0;
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkStatusEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedFederationEntityMetadataGetFederationTrustMarkStatusEndpoint)(m); }
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkStatusEndpoint_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedFederationEntityMetadataGetFederationTrustMarkStatusEndpoint)(m); };

static void (*OIFFn_oidfedFederationEntityMetadataSetFederationTrustMarkStatusEndpoint)(struct oidfed_federation_entity_metadata m, char* endpoint) = 0;
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkStatusEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* endpoint) { OIDFED_MAYLOAD_REQUEST(, oidfedFederationEntityMetadataSetFederationTrustMarkStatusEndpoint)(m, endpoint); }
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkStatusEndpoint_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m, char* endpoint) { OIDFED_MAYLOAD_SERVER(, oidfedFederationEntityMetadataSetFederationTrustMarkStatusEndpoint)(m, endpoint); };

static char* (*OIFFn_oidfedFederationEntityMetadataGetFederationTrustMarkListEndpoint)(struct oidfed_federation_entity_metadata m) = 0;
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkListEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedFederationEntityMetadataGetFederationTrustMarkListEndpoint)(m); }
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkListEndpoint_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedFederationEntityMetadataGetFederationTrustMarkListEndpoint)(m); };

static void (*OIFFn_oidfedFederationEntityMetadataSetFederationTrustMarkListEndpoint)(struct oidfed_federation_entity_metadata m, char* endpoint) = 0;
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkListEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* endpoint) { OIDFED_MAYLOAD_REQUEST(, oidfedFederationEntityMetadataSetFederationTrustMarkListEndpoint)(m, endpoint); }
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkListEndpoint_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m, char* endpoint) { OIDFED_MAYLOAD_SERVER(, oidfedFederationEntityMetadataSetFederationTrustMarkListEndpoint)(m, endpoint); };

static char* (*OIFFn_oidfedFederationEntityMetadataGetFederationTrustMarkEndpoint)(struct oidfed_federation_entity_metadata m) = 0;
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedFederationEntityMetadataGetFederationTrustMarkEndpoint)(m); }
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationTrustMarkEndpoint_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedFederationEntityMetadataGetFederationTrustMarkEndpoint)(m); };

static void (*OIFFn_oidfedFederationEntityMetadataSetFederationTrustMarkEndpoint)(struct oidfed_federation_entity_metadata m, char* endpoint) = 0;
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* endpoint) { OIDFED_MAYLOAD_REQUEST(, oidfedFederationEntityMetadataSetFederationTrustMarkEndpoint)(m, endpoint); }
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationTrustMarkEndpoint_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m, char* endpoint) { OIDFED_MAYLOAD_SERVER(, oidfedFederationEntityMetadataSetFederationTrustMarkEndpoint)(m, endpoint); };

static char* (*OIFFn_oidfedFederationEntityMetadataGetFederationHistoricalKeysEndpoint)(struct oidfed_federation_entity_metadata m) = 0;
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationHistoricalKeysEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedFederationEntityMetadataGetFederationHistoricalKeysEndpoint)(m); }
char* OIFMayLoad_oidfedFederationEntityMetadataGetFederationHistoricalKeysEndpoint_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedFederationEntityMetadataGetFederationHistoricalKeysEndpoint)(m); };

static void (*OIFFn_oidfedFederationEntityMetadataSetFederationHistoricalKeysEndpoint)(struct oidfed_federation_entity_metadata m, char* endpoint) = 0;
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationHistoricalKeysEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* endpoint) { OIDFED_MAYLOAD_REQUEST(, oidfedFederationEntityMetadataSetFederationHistoricalKeysEndpoint)(m, endpoint); }
void OIFMayLoad_oidfedFederationEntityMetadataSetFederationHistoricalKeysEndpoint_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m, char* endpoint) { OIDFED_MAYLOAD_SERVER(, oidfedFederationEntityMetadataSetFederationHistoricalKeysEndpoint)(m, endpoint); };

static char* (*OIFFn_oidfedFederationEntityMetadataGetLogoURI)(struct oidfed_federation_entity_metadata m) = 0;
char* OIFMayLoad_oidfedFederationEntityMetadataGetLogoURI_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedFederationEntityMetadataGetLogoURI)(m); }
char* OIFMayLoad_oidfedFederationEntityMetadataGetLogoURI_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedFederationEntityMetadataGetLogoURI)(m); };

static void (*OIFFn_oidfedFederationEntityMetadataSetLogoURI)(struct oidfed_federation_entity_metadata m, char* logoURI) = 0;
void OIFMayLoad_oidfedFederationEntityMetadataSetLogoURI_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* logoURI) { OIDFED_MAYLOAD_REQUEST(, oidfedFederationEntityMetadataSetLogoURI)(m, logoURI); }
void OIFMayLoad_oidfedFederationEntityMetadataSetLogoURI_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m, char* logoURI) { OIDFED_MAYLOAD_SERVER(, oidfedFederationEntityMetadataSetLogoURI)(m, logoURI); };

static char* (*OIFFn_oidfedFederationEntityMetadataGetPolicyURI)(struct oidfed_federation_entity_metadata m) = 0;
char* OIFMayLoad_oidfedFederationEntityMetadataGetPolicyURI_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedFederationEntityMetadataGetPolicyURI)(m); }
char* OIFMayLoad_oidfedFederationEntityMetadataGetPolicyURI_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedFederationEntityMetadataGetPolicyURI)(m); };

static void (*OIFFn_oidfedFederationEntityMetadataSetPolicyURI)(struct oidfed_federation_entity_metadata m, char* policyURI) = 0;
void OIFMayLoad_oidfedFederationEntityMetadataSetPolicyURI_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* policyURI) { OIDFED_MAYLOAD_REQUEST(, oidfedFederationEntityMetadataSetPolicyURI)(m, policyURI); }
void OIFMayLoad_oidfedFederationEntityMetadataSetPolicyURI_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m, char* policyURI) { OIDFED_MAYLOAD_SERVER(, oidfedFederationEntityMetadataSetPolicyURI)(m, policyURI); };

static char* (*OIFFn_oidfedFederationEntityMetadataGetInformationURI)(struct oidfed_federation_entity_metadata m) = 0;
char* OIFMayLoad_oidfedFederationEntityMetadataGetInformationURI_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedFederationEntityMetadataGetInformationURI)(m); }
char* OIFMayLoad_oidfedFederationEntityMetadataGetInformationURI_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedFederationEntityMetadataGetInformationURI)(m); };

static void (*OIFFn_oidfedFederationEntityMetadataSetInformationURI)(struct oidfed_federation_entity_metadata m, char* informationURI) = 0;
void OIFMayLoad_oidfedFederationEntityMetadataSetInformationURI_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* informationURI) { OIDFED_MAYLOAD_REQUEST(, oidfedFederationEntityMetadataSetInformationURI)(m, informationURI); }
void OIFMayLoad_oidfedFederationEntityMetadataSetInformationURI_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m, char* informationURI) { OIDFED_MAYLOAD_SERVER(, oidfedFederationEntityMetadataSetInformationURI)(m, informationURI); };

static char* (*OIFFn_oidfedFederationEntityMetadataGetOrganizationName)(struct oidfed_federation_entity_metadata m) = 0;
char* OIFMayLoad_oidfedFederationEntityMetadataGetOrganizationName_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedFederationEntityMetadataGetOrganizationName)(m); }
char* OIFMayLoad_oidfedFederationEntityMetadataGetOrganizationName_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedFederationEntityMetadataGetOrganizationName)(m); };

static void (*OIFFn_oidfedFederationEntityMetadataSetOrganizationName)(struct oidfed_federation_entity_metadata m, char* organizationName) = 0;
void OIFMayLoad_oidfedFederationEntityMetadataSetOrganizationName_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* organizationName) { OIDFED_MAYLOAD_REQUEST(, oidfedFederationEntityMetadataSetOrganizationName)(m, organizationName); }
void OIFMayLoad_oidfedFederationEntityMetadataSetOrganizationName_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m, char* organizationName) { OIDFED_MAYLOAD_SERVER(, oidfedFederationEntityMetadataSetOrganizationName)(m, organizationName); };

static char* (*OIFFn_oidfedFederationEntityMetadataGetOrganizationURL)(struct oidfed_federation_entity_metadata m) = 0;
char* OIFMayLoad_oidfedFederationEntityMetadataGetOrganizationURL_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedFederationEntityMetadataGetOrganizationURL)(m); }
char* OIFMayLoad_oidfedFederationEntityMetadataGetOrganizationURL_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedFederationEntityMetadataGetOrganizationURL)(m); };

static void (*OIFFn_oidfedFederationEntityMetadataSetOrganizationURL)(struct oidfed_federation_entity_metadata m, char* organizationURL) = 0;
void OIFMayLoad_oidfedFederationEntityMetadataSetOrganizationURL_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata m, char* organizationURL) { OIDFED_MAYLOAD_REQUEST(, oidfedFederationEntityMetadataSetOrganizationURL)(m, organizationURL); }
void OIFMayLoad_oidfedFederationEntityMetadataSetOrganizationURL_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata m, char* organizationURL) { OIDFED_MAYLOAD_SERVER(, oidfedFederationEntityMetadataSetOrganizationURL)(m, organizationURL); };

static void (*OIFFn_oidfedFederationEntityMetadataDestroy)(struct oidfed_federation_entity_metadata* m) = 0;
void OIFMayLoad_oidfedFederationEntityMetadataDestroy_request(request_rec* wrap_request_ctx, struct oidfed_federation_entity_metadata* m) { OIDFED_MAYLOAD_REQUEST(, oidfedFederationEntityMetadataDestroy)(m); }
void OIFMayLoad_oidfedFederationEntityMetadataDestroy_server(server_rec* wrap_server_ctx, struct oidfed_federation_entity_metadata* m) { OIDFED_MAYLOAD_SERVER(, oidfedFederationEntityMetadataDestroy)(m); };

static struct oidfed_federation_leaf (*OIFFn_oidfedFederationLeafCreate)(char* entityID, char** authorityHints, size_t authorityHintsCount, struct oidfed_trust_anchor* trustAnchors, size_t trustAnchorsCount, struct oidfed_versatile_signer federationSigner, struct oidfed_versatile_signer oidcSigner, struct oidfed_metadata metadata, int* errc) = 0;
struct oidfed_federation_leaf OIFMayLoad_oidfedFederationLeafCreate_request(request_rec* wrap_request_ctx, char* entityID, char** authorityHints, size_t authorityHintsCount, struct oidfed_trust_anchor* trustAnchors, size_t trustAnchorsCount, struct oidfed_versatile_signer federationSigner, struct oidfed_versatile_signer oidcSigner, struct oidfed_metadata metadata, int* errc) { OIDFED_MAYLOAD_REQUEST(return, oidfedFederationLeafCreate)(entityID, authorityHints, authorityHintsCount, trustAnchors, trustAnchorsCount, federationSigner, oidcSigner, metadata, errc); }
struct oidfed_federation_leaf OIFMayLoad_oidfedFederationLeafCreate_server(server_rec* wrap_server_ctx, char* entityID, char** authorityHints, size_t authorityHintsCount, struct oidfed_trust_anchor* trustAnchors, size_t trustAnchorsCount, struct oidfed_versatile_signer federationSigner, struct oidfed_versatile_signer oidcSigner, struct oidfed_metadata metadata, int* errc) { OIDFED_MAYLOAD_SERVER(return, oidfedFederationLeafCreate)(entityID, authorityHints, authorityHintsCount, trustAnchors, trustAnchorsCount, federationSigner, oidcSigner, metadata, errc); };

static void (*OIFFn_oidfedFederationLeafDestroy)(struct oidfed_federation_leaf* leaf) = 0;
void OIFMayLoad_oidfedFederationLeafDestroy_request(request_rec* wrap_request_ctx, struct oidfed_federation_leaf* leaf) { OIDFED_MAYLOAD_REQUEST(, oidfedFederationLeafDestroy)(leaf); }
void OIFMayLoad_oidfedFederationLeafDestroy_server(server_rec* wrap_server_ctx, struct oidfed_federation_leaf* leaf) { OIDFED_MAYLOAD_SERVER(, oidfedFederationLeafDestroy)(leaf); };

static int (*OIFFn_oidfedFederationLeafGetAsJWT)(struct oidfed_federation_leaf leaf, char** bytes, size_t* bytesCount) = 0;
int OIFMayLoad_oidfedFederationLeafGetAsJWT_request(request_rec* wrap_request_ctx, struct oidfed_federation_leaf leaf, char** bytes, size_t* bytesCount) { OIDFED_MAYLOAD_REQUEST(return, oidfedFederationLeafGetAsJWT)(leaf, bytes, bytesCount); }
int OIFMayLoad_oidfedFederationLeafGetAsJWT_server(server_rec* wrap_server_ctx, struct oidfed_federation_leaf leaf, char** bytes, size_t* bytesCount) { OIDFED_MAYLOAD_SERVER(return, oidfedFederationLeafGetAsJWT)(leaf, bytes, bytesCount); };

static struct oidfed_request_producer (*OIFFn_oidfedFederationLeafGetRequestObjectProducer)(struct oidfed_federation_leaf leaf) = 0;
struct oidfed_request_producer OIFMayLoad_oidfedFederationLeafGetRequestObjectProducer_request(request_rec* wrap_request_ctx, struct oidfed_federation_leaf leaf) { OIDFED_MAYLOAD_REQUEST(return, oidfedFederationLeafGetRequestObjectProducer)(leaf); }
struct oidfed_request_producer OIFMayLoad_oidfedFederationLeafGetRequestObjectProducer_server(server_rec* wrap_server_ctx, struct oidfed_federation_leaf leaf) { OIDFED_MAYLOAD_SERVER(return, oidfedFederationLeafGetRequestObjectProducer)(leaf); };

static struct oidfed_jws_headers (*OIFFn_oidfedJWSHeadersCreate)() = 0;
struct oidfed_jws_headers OIFMayLoad_oidfedJWSHeadersCreate_request(request_rec* wrap_request_ctx) { OIDFED_MAYLOAD_REQUEST(return, oidfedJWSHeadersCreate)(); }
struct oidfed_jws_headers OIFMayLoad_oidfedJWSHeadersCreate_server(server_rec* wrap_server_ctx) { OIDFED_MAYLOAD_SERVER(return, oidfedJWSHeadersCreate)(); };

static void (*OIFFn_oidfedJWSHeadersDestroy)(struct oidfed_jws_headers* h) = 0;
void OIFMayLoad_oidfedJWSHeadersDestroy_request(request_rec* wrap_request_ctx, struct oidfed_jws_headers* h) { OIDFED_MAYLOAD_REQUEST(, oidfedJWSHeadersDestroy)(h); }
void OIFMayLoad_oidfedJWSHeadersDestroy_server(server_rec* wrap_server_ctx, struct oidfed_jws_headers* h) { OIDFED_MAYLOAD_SERVER(, oidfedJWSHeadersDestroy)(h); };

static int (*OIFFn_oidfedJWSHeadersSet)(struct oidfed_jws_headers h, char* key, char* value) = 0;
int OIFMayLoad_oidfedJWSHeadersSet_request(request_rec* wrap_request_ctx, struct oidfed_jws_headers h, char* key, char* value) { OIDFED_MAYLOAD_REQUEST(return, oidfedJWSHeadersSet)(h, key, value); }
int OIFMayLoad_oidfedJWSHeadersSet_server(server_rec* wrap_server_ctx, struct oidfed_jws_headers h, char* key, char* value) { OIDFED_MAYLOAD_SERVER(return, oidfedJWSHeadersSet)(h, key, value); };

static struct oidfed_map (*OIFFn_oidfCreateMap)() = 0;
struct oidfed_map OIFMayLoad_oidfCreateMap_request(request_rec* wrap_request_ctx) { OIDFED_MAYLOAD_REQUEST(return, oidfCreateMap)(); }
struct oidfed_map OIFMayLoad_oidfCreateMap_server(server_rec* wrap_server_ctx) { OIDFED_MAYLOAD_SERVER(return, oidfCreateMap)(); };

static _Bool (*OIFFn_oidfMapHasKey)(struct oidfed_map m, char* key) = 0;
_Bool OIFMayLoad_oidfMapHasKey_request(request_rec* wrap_request_ctx, struct oidfed_map m, char* key) { OIDFED_MAYLOAD_REQUEST(return, oidfMapHasKey)(m, key); }
_Bool OIFMayLoad_oidfMapHasKey_server(server_rec* wrap_server_ctx, struct oidfed_map m, char* key) { OIDFED_MAYLOAD_SERVER(return, oidfMapHasKey)(m, key); };

static void (*OIFFn_oidfMapSetString)(struct oidfed_map m, char* key, char* value) = 0;
void OIFMayLoad_oidfMapSetString_request(request_rec* wrap_request_ctx, struct oidfed_map m, char* key, char* value) { OIDFED_MAYLOAD_REQUEST(, oidfMapSetString)(m, key, value); }
void OIFMayLoad_oidfMapSetString_server(server_rec* wrap_server_ctx, struct oidfed_map m, char* key, char* value) { OIDFED_MAYLOAD_SERVER(, oidfMapSetString)(m, key, value); };

static void (*OIFFn_oidfMapSetInt64)(struct oidfed_map m, char* key, int64_t value) = 0;
void OIFMayLoad_oidfMapSetInt64_request(request_rec* wrap_request_ctx, struct oidfed_map m, char* key, int64_t value) { OIDFED_MAYLOAD_REQUEST(, oidfMapSetInt64)(m, key, value); }
void OIFMayLoad_oidfMapSetInt64_server(server_rec* wrap_server_ctx, struct oidfed_map m, char* key, int64_t value) { OIDFED_MAYLOAD_SERVER(, oidfMapSetInt64)(m, key, value); };

static void (*OIFFn_oidfMapDestroy)(struct oidfed_map* m) = 0;
void OIFMayLoad_oidfMapDestroy_request(request_rec* wrap_request_ctx, struct oidfed_map* m) { OIDFED_MAYLOAD_REQUEST(, oidfMapDestroy)(m); }
void OIFMayLoad_oidfMapDestroy_server(server_rec* wrap_server_ctx, struct oidfed_map* m) { OIDFED_MAYLOAD_SERVER(, oidfMapDestroy)(m); };

static struct oidfed_metadata (*OIFFn_oidfedMetadataCreate)() = 0;
struct oidfed_metadata OIFMayLoad_oidfedMetadataCreate_request(request_rec* wrap_request_ctx) { OIDFED_MAYLOAD_REQUEST(return, oidfedMetadataCreate)(); }
struct oidfed_metadata OIFMayLoad_oidfedMetadataCreate_server(server_rec* wrap_server_ctx) { OIDFED_MAYLOAD_SERVER(return, oidfedMetadataCreate)(); };

static struct oidfed_openid_provider_metadata (*OIFFn_oidfedMetadataGetOPMetadata)(struct oidfed_metadata m) = 0;
struct oidfed_openid_provider_metadata OIFMayLoad_oidfedMetadataGetOPMetadata_request(request_rec* wrap_request_ctx, struct oidfed_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedMetadataGetOPMetadata)(m); }
struct oidfed_openid_provider_metadata OIFMayLoad_oidfedMetadataGetOPMetadata_server(server_rec* wrap_server_ctx, struct oidfed_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedMetadataGetOPMetadata)(m); };

static void (*OIFFn_oidfedMetadataSetOPMetadata)(struct oidfed_metadata m, struct oidfed_openid_provider_metadata op) = 0;
void OIFMayLoad_oidfedMetadataSetOPMetadata_request(request_rec* wrap_request_ctx, struct oidfed_metadata m, struct oidfed_openid_provider_metadata op) { OIDFED_MAYLOAD_REQUEST(, oidfedMetadataSetOPMetadata)(m, op); }
void OIFMayLoad_oidfedMetadataSetOPMetadata_server(server_rec* wrap_server_ctx, struct oidfed_metadata m, struct oidfed_openid_provider_metadata op) { OIDFED_MAYLOAD_SERVER(, oidfedMetadataSetOPMetadata)(m, op); };

static uintptr_t (*OIFFn_oidfedMetadataGetRPMetadata)(struct oidfed_metadata m) = 0;
uintptr_t OIFMayLoad_oidfedMetadataGetRPMetadata_request(request_rec* wrap_request_ctx, struct oidfed_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedMetadataGetRPMetadata)(m); }
uintptr_t OIFMayLoad_oidfedMetadataGetRPMetadata_server(server_rec* wrap_server_ctx, struct oidfed_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedMetadataGetRPMetadata)(m); };

static void (*OIFFn_oidfedMetadataSetRPMetadata)(struct oidfed_metadata m, uintptr_t rp) = 0;
void OIFMayLoad_oidfedMetadataSetRPMetadata_request(request_rec* wrap_request_ctx, struct oidfed_metadata m, uintptr_t rp) { OIDFED_MAYLOAD_REQUEST(, oidfedMetadataSetRPMetadata)(m, rp); }
void OIFMayLoad_oidfedMetadataSetRPMetadata_server(server_rec* wrap_server_ctx, struct oidfed_metadata m, uintptr_t rp) { OIDFED_MAYLOAD_SERVER(, oidfedMetadataSetRPMetadata)(m, rp); };

static uintptr_t (*OIFFn_oidfedMetadataGetFederationEntityMetadata)(struct oidfed_metadata m) = 0;
uintptr_t OIFMayLoad_oidfedMetadataGetFederationEntityMetadata_request(request_rec* wrap_request_ctx, struct oidfed_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedMetadataGetFederationEntityMetadata)(m); }
uintptr_t OIFMayLoad_oidfedMetadataGetFederationEntityMetadata_server(server_rec* wrap_server_ctx, struct oidfed_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedMetadataGetFederationEntityMetadata)(m); };

static void (*OIFFn_oidfedMetadataSetFederationEntityMetadata)(struct oidfed_metadata m, uintptr_t fe) = 0;
void OIFMayLoad_oidfedMetadataSetFederationEntityMetadata_request(request_rec* wrap_request_ctx, struct oidfed_metadata m, uintptr_t fe) { OIDFED_MAYLOAD_REQUEST(, oidfedMetadataSetFederationEntityMetadata)(m, fe); }
void OIFMayLoad_oidfedMetadataSetFederationEntityMetadata_server(server_rec* wrap_server_ctx, struct oidfed_metadata m, uintptr_t fe) { OIDFED_MAYLOAD_SERVER(, oidfedMetadataSetFederationEntityMetadata)(m, fe); };

static char* (*OIFFn_oidfedOpenIDProviderMetadataGetAuthorizationEndpoint)(struct oidfed_openid_provider_metadata m) = 0;
char* OIFMayLoad_oidfedOpenIDProviderMetadataGetAuthorizationEndpoint_request(request_rec* wrap_request_ctx, struct oidfed_openid_provider_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedOpenIDProviderMetadataGetAuthorizationEndpoint)(m); }
char* OIFMayLoad_oidfedOpenIDProviderMetadataGetAuthorizationEndpoint_server(server_rec* wrap_server_ctx, struct oidfed_openid_provider_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedOpenIDProviderMetadataGetAuthorizationEndpoint)(m); };

static char* (*OIFFn_oidfedOpenIDProviderMetadataGetIssuer)(struct oidfed_openid_provider_metadata m) = 0;
char* OIFMayLoad_oidfedOpenIDProviderMetadataGetIssuer_request(request_rec* wrap_request_ctx, struct oidfed_openid_provider_metadata m) { OIDFED_MAYLOAD_REQUEST(return, oidfedOpenIDProviderMetadataGetIssuer)(m); }
char* OIFMayLoad_oidfedOpenIDProviderMetadataGetIssuer_server(server_rec* wrap_server_ctx, struct oidfed_openid_provider_metadata m) { OIDFED_MAYLOAD_SERVER(return, oidfedOpenIDProviderMetadataGetIssuer)(m); };

static void (*OIFFn_oidfedOpenIDProviderMetadataDestroy)(struct oidfed_openid_provider_metadata* m) = 0;
void OIFMayLoad_oidfedOpenIDProviderMetadataDestroy_request(request_rec* wrap_request_ctx, struct oidfed_openid_provider_metadata* m) { OIDFED_MAYLOAD_REQUEST(, oidfedOpenIDProviderMetadataDestroy)(m); }
void OIFMayLoad_oidfedOpenIDProviderMetadataDestroy_server(server_rec* wrap_server_ctx, struct oidfed_openid_provider_metadata* m) { OIDFED_MAYLOAD_SERVER(, oidfedOpenIDProviderMetadataDestroy)(m); };

static struct oidfed_openid_relying_party_metadata (*OIFFn_oidfedOpenIDRelyingPartyMetadataCreate)() = 0;
struct oidfed_openid_relying_party_metadata OIFMayLoad_oidfedOpenIDRelyingPartyMetadataCreate_request(request_rec* wrap_request_ctx) { OIDFED_MAYLOAD_REQUEST(return, oidfedOpenIDRelyingPartyMetadataCreate)(); }
struct oidfed_openid_relying_party_metadata OIFMayLoad_oidfedOpenIDRelyingPartyMetadataCreate_server(server_rec* wrap_server_ctx) { OIDFED_MAYLOAD_SERVER(return, oidfedOpenIDRelyingPartyMetadataCreate)(); };

static char* (*OIFFn_oidfedOpenIDRelyingPartyMetadataGetClientID)(struct oidfed_openid_relying_party_metadata rp) = 0;
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetClientID_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp) { OIDFED_MAYLOAD_REQUEST(return, oidfedOpenIDRelyingPartyMetadataGetClientID)(rp); }
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetClientID_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp) { OIDFED_MAYLOAD_SERVER(return, oidfedOpenIDRelyingPartyMetadataGetClientID)(rp); };

static void (*OIFFn_oidfedOpenIDRelyingPartyMetadataSetClientID)(struct oidfed_openid_relying_party_metadata rp, char* clientID) = 0;
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientID_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char* clientID) { OIDFED_MAYLOAD_REQUEST(, oidfedOpenIDRelyingPartyMetadataSetClientID)(rp, clientID); }
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientID_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp, char* clientID) { OIDFED_MAYLOAD_SERVER(, oidfedOpenIDRelyingPartyMetadataSetClientID)(rp, clientID); };

static char* (*OIFFn_oidfedOpenIDRelyingPartyMetadataGetClientName)(struct oidfed_openid_relying_party_metadata rp) = 0;
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetClientName_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp) { OIDFED_MAYLOAD_REQUEST(return, oidfedOpenIDRelyingPartyMetadataGetClientName)(rp); }
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetClientName_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp) { OIDFED_MAYLOAD_SERVER(return, oidfedOpenIDRelyingPartyMetadataGetClientName)(rp); };

static void (*OIFFn_oidfedOpenIDRelyingPartyMetadataSetClientName)(struct oidfed_openid_relying_party_metadata rp, char* clientName) = 0;
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientName_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char* clientName) { OIDFED_MAYLOAD_REQUEST(, oidfedOpenIDRelyingPartyMetadataSetClientName)(rp, clientName); }
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientName_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp, char* clientName) { OIDFED_MAYLOAD_SERVER(, oidfedOpenIDRelyingPartyMetadataSetClientName)(rp, clientName); };

static void (*OIFFn_oidfedOpenIDRelyingPartyMetadataSetRedirectUris)(struct oidfed_openid_relying_party_metadata rp, char** uris, size_t count) = 0;
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetRedirectUris_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char** uris, size_t count) { OIDFED_MAYLOAD_REQUEST(, oidfedOpenIDRelyingPartyMetadataSetRedirectUris)(rp, uris, count); }
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetRedirectUris_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp, char** uris, size_t count) { OIDFED_MAYLOAD_SERVER(, oidfedOpenIDRelyingPartyMetadataSetRedirectUris)(rp, uris, count); };

static void (*OIFFn_oidfedOpenIDRelyingPartyMetadataSetResponseTypes)(struct oidfed_openid_relying_party_metadata rp, char** types, size_t count) = 0;
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetResponseTypes_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char** types, size_t count) { OIDFED_MAYLOAD_REQUEST(, oidfedOpenIDRelyingPartyMetadataSetResponseTypes)(rp, types, count); }
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetResponseTypes_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp, char** types, size_t count) { OIDFED_MAYLOAD_SERVER(, oidfedOpenIDRelyingPartyMetadataSetResponseTypes)(rp, types, count); };

static void (*OIFFn_oidfedOpenIDRelyingPartyMetadataSetGrantTypes)(struct oidfed_openid_relying_party_metadata rp, char** types, size_t count) = 0;
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetGrantTypes_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char** types, size_t count) { OIDFED_MAYLOAD_REQUEST(, oidfedOpenIDRelyingPartyMetadataSetGrantTypes)(rp, types, count); }
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetGrantTypes_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp, char** types, size_t count) { OIDFED_MAYLOAD_SERVER(, oidfedOpenIDRelyingPartyMetadataSetGrantTypes)(rp, types, count); };

static char* (*OIFFn_oidfedOpenIDRelyingPartyMetadataGetApplicationType)(struct oidfed_openid_relying_party_metadata rp) = 0;
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetApplicationType_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp) { OIDFED_MAYLOAD_REQUEST(return, oidfedOpenIDRelyingPartyMetadataGetApplicationType)(rp); }
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetApplicationType_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp) { OIDFED_MAYLOAD_SERVER(return, oidfedOpenIDRelyingPartyMetadataGetApplicationType)(rp); };

static void (*OIFFn_oidfedOpenIDRelyingPartyMetadataSetApplicationType)(struct oidfed_openid_relying_party_metadata rp, char* applicationType) = 0;
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetApplicationType_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char* applicationType) { OIDFED_MAYLOAD_REQUEST(, oidfedOpenIDRelyingPartyMetadataSetApplicationType)(rp, applicationType); }
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetApplicationType_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp, char* applicationType) { OIDFED_MAYLOAD_SERVER(, oidfedOpenIDRelyingPartyMetadataSetApplicationType)(rp, applicationType); };

static char* (*OIFFn_oidfedOpenIDRelyingPartyMetadataGetLogoURI)(struct oidfed_openid_relying_party_metadata rp) = 0;
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetLogoURI_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp) { OIDFED_MAYLOAD_REQUEST(return, oidfedOpenIDRelyingPartyMetadataGetLogoURI)(rp); }
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetLogoURI_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp) { OIDFED_MAYLOAD_SERVER(return, oidfedOpenIDRelyingPartyMetadataGetLogoURI)(rp); };

static void (*OIFFn_oidfedOpenIDRelyingPartyMetadataSetLogoURI)(struct oidfed_openid_relying_party_metadata rp, char* logoURI) = 0;
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetLogoURI_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char* logoURI) { OIDFED_MAYLOAD_REQUEST(, oidfedOpenIDRelyingPartyMetadataSetLogoURI)(rp, logoURI); }
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetLogoURI_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp, char* logoURI) { OIDFED_MAYLOAD_SERVER(, oidfedOpenIDRelyingPartyMetadataSetLogoURI)(rp, logoURI); };

static uintptr_t (*OIFFn_oidfedOpenIDRelyingPartyMetadataGetJWKS)(struct oidfed_openid_relying_party_metadata rp) = 0;
uintptr_t OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetJWKS_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp) { OIDFED_MAYLOAD_REQUEST(return, oidfedOpenIDRelyingPartyMetadataGetJWKS)(rp); }
uintptr_t OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetJWKS_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp) { OIDFED_MAYLOAD_SERVER(return, oidfedOpenIDRelyingPartyMetadataGetJWKS)(rp); };

static void (*OIFFn_oidfedOpenIDRelyingPartyMetadataSetJWKS)(struct oidfed_openid_relying_party_metadata rp, uintptr_t jwks) = 0;
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetJWKS_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, uintptr_t jwks) { OIDFED_MAYLOAD_REQUEST(, oidfedOpenIDRelyingPartyMetadataSetJWKS)(rp, jwks); }
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetJWKS_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp, uintptr_t jwks) { OIDFED_MAYLOAD_SERVER(, oidfedOpenIDRelyingPartyMetadataSetJWKS)(rp, jwks); };

static void (*OIFFn_oidfedOpenIDRelyingPartyMetadataSetJWKSFromKeyStorage)(struct oidfed_openid_relying_party_metadata rp, struct oidfed_single_key_storage storage) = 0;
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetJWKSFromKeyStorage_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, struct oidfed_single_key_storage storage) { OIDFED_MAYLOAD_REQUEST(, oidfedOpenIDRelyingPartyMetadataSetJWKSFromKeyStorage)(rp, storage); }
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetJWKSFromKeyStorage_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp, struct oidfed_single_key_storage storage) { OIDFED_MAYLOAD_SERVER(, oidfedOpenIDRelyingPartyMetadataSetJWKSFromKeyStorage)(rp, storage); };

static char* (*OIFFn_oidfedOpenIDRelyingPartyMetadataGetOrganizationName)(struct oidfed_openid_relying_party_metadata rp) = 0;
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetOrganizationName_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp) { OIDFED_MAYLOAD_REQUEST(return, oidfedOpenIDRelyingPartyMetadataGetOrganizationName)(rp); }
char* OIFMayLoad_oidfedOpenIDRelyingPartyMetadataGetOrganizationName_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp) { OIDFED_MAYLOAD_SERVER(return, oidfedOpenIDRelyingPartyMetadataGetOrganizationName)(rp); };

static void (*OIFFn_oidfedOpenIDRelyingPartyMetadataSetOrganizationName)(struct oidfed_openid_relying_party_metadata rp, char* organizationName) = 0;
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetOrganizationName_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char* organizationName) { OIDFED_MAYLOAD_REQUEST(, oidfedOpenIDRelyingPartyMetadataSetOrganizationName)(rp, organizationName); }
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetOrganizationName_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp, char* organizationName) { OIDFED_MAYLOAD_SERVER(, oidfedOpenIDRelyingPartyMetadataSetOrganizationName)(rp, organizationName); };

static void (*OIFFn_oidfedOpenIDRelyingPartyMetadataSetClientRegistrationTypes)(struct oidfed_openid_relying_party_metadata rp, char** types, size_t count) = 0;
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientRegistrationTypes_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata rp, char** types, size_t count) { OIDFED_MAYLOAD_REQUEST(, oidfedOpenIDRelyingPartyMetadataSetClientRegistrationTypes)(rp, types, count); }
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataSetClientRegistrationTypes_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata rp, char** types, size_t count) { OIDFED_MAYLOAD_SERVER(, oidfedOpenIDRelyingPartyMetadataSetClientRegistrationTypes)(rp, types, count); };

static void (*OIFFn_oidfedOpenIDRelyingPartyMetadataDestroy)(struct oidfed_openid_relying_party_metadata* rp) = 0;
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataDestroy_request(request_rec* wrap_request_ctx, struct oidfed_openid_relying_party_metadata* rp) { OIDFED_MAYLOAD_REQUEST(, oidfedOpenIDRelyingPartyMetadataDestroy)(rp); }
void OIFMayLoad_oidfedOpenIDRelyingPartyMetadataDestroy_server(server_rec* wrap_server_ctx, struct oidfed_openid_relying_party_metadata* rp) { OIDFED_MAYLOAD_SERVER(, oidfedOpenIDRelyingPartyMetadataDestroy)(rp); };

static struct oidfed_request_producer (*OIFFn_oidfedRequestProducerCreate)(char* entityId, int64_t duration, struct oidfed_versatile_signer signer) = 0;
struct oidfed_request_producer OIFMayLoad_oidfedRequestProducerCreate_request(request_rec* wrap_request_ctx, char* entityId, int64_t duration, struct oidfed_versatile_signer signer) { OIDFED_MAYLOAD_REQUEST(return, oidfedRequestProducerCreate)(entityId, duration, signer); }
struct oidfed_request_producer OIFMayLoad_oidfedRequestProducerCreate_server(server_rec* wrap_server_ctx, char* entityId, int64_t duration, struct oidfed_versatile_signer signer) { OIDFED_MAYLOAD_SERVER(return, oidfedRequestProducerCreate)(entityId, duration, signer); };

static void (*OIFFn_oidfedRequestProducerDestroy)(struct oidfed_request_producer* producer) = 0;
void OIFMayLoad_oidfedRequestProducerDestroy_request(request_rec* wrap_request_ctx, struct oidfed_request_producer* producer) { OIDFED_MAYLOAD_REQUEST(, oidfedRequestProducerDestroy)(producer); }
void OIFMayLoad_oidfedRequestProducerDestroy_server(server_rec* wrap_server_ctx, struct oidfed_request_producer* producer) { OIDFED_MAYLOAD_SERVER(, oidfedRequestProducerDestroy)(producer); };

static struct oidfed_signed_bytes (*OIFFn_oidfedRequestProducerProduceObject)(struct oidfed_request_producer producer, struct oidfed_map requestValues, struct oidfed_jws_headers headers, char** algorithms, size_t algorithmsCount, int* errc) = 0;
struct oidfed_signed_bytes OIFMayLoad_oidfedRequestProducerProduceObject_request(request_rec* wrap_request_ctx, struct oidfed_request_producer producer, struct oidfed_map requestValues, struct oidfed_jws_headers headers, char** algorithms, size_t algorithmsCount, int* errc) { OIDFED_MAYLOAD_REQUEST(return, oidfedRequestProducerProduceObject)(producer, requestValues, headers, algorithms, algorithmsCount, errc); }
struct oidfed_signed_bytes OIFMayLoad_oidfedRequestProducerProduceObject_server(server_rec* wrap_server_ctx, struct oidfed_request_producer producer, struct oidfed_map requestValues, struct oidfed_jws_headers headers, char** algorithms, size_t algorithmsCount, int* errc) { OIDFED_MAYLOAD_SERVER(return, oidfedRequestProducerProduceObject)(producer, requestValues, headers, algorithms, algorithmsCount, errc); };

static struct oidfed_signed_bytes (*OIFFn_oidfedRequestProducerClientAssertion)(struct oidfed_request_producer producer, char* audience, char** algorithms, size_t algorithmsCount, int* errc) = 0;
struct oidfed_signed_bytes OIFMayLoad_oidfedRequestProducerClientAssertion_request(request_rec* wrap_request_ctx, struct oidfed_request_producer producer, char* audience, char** algorithms, size_t algorithmsCount, int* errc) { OIDFED_MAYLOAD_REQUEST(return, oidfedRequestProducerClientAssertion)(producer, audience, algorithms, algorithmsCount, errc); }
struct oidfed_signed_bytes OIFMayLoad_oidfedRequestProducerClientAssertion_server(server_rec* wrap_server_ctx, struct oidfed_request_producer producer, char* audience, char** algorithms, size_t algorithmsCount, int* errc) { OIDFED_MAYLOAD_SERVER(return, oidfedRequestProducerClientAssertion)(producer, audience, algorithms, algorithmsCount, errc); };

static void (*OIFFn_oidfedSignedBytesDestroy)(struct oidfed_signed_bytes* sb) = 0;
void OIFMayLoad_oidfedSignedBytesDestroy_request(request_rec* wrap_request_ctx, struct oidfed_signed_bytes* sb) { OIDFED_MAYLOAD_REQUEST(, oidfedSignedBytesDestroy)(sb); }
void OIFMayLoad_oidfedSignedBytesDestroy_server(server_rec* wrap_server_ctx, struct oidfed_signed_bytes* sb) { OIDFED_MAYLOAD_SERVER(, oidfedSignedBytesDestroy)(sb); };

static char* (*OIFFn_oidfedSignedBytesGetData)(struct oidfed_signed_bytes sb, size_t* count) = 0;
char* OIFMayLoad_oidfedSignedBytesGetData_request(request_rec* wrap_request_ctx, struct oidfed_signed_bytes sb, size_t* count) { OIDFED_MAYLOAD_REQUEST(return, oidfedSignedBytesGetData)(sb, count); }
char* OIFMayLoad_oidfedSignedBytesGetData_server(server_rec* wrap_server_ctx, struct oidfed_signed_bytes sb, size_t* count) { OIDFED_MAYLOAD_SERVER(return, oidfedSignedBytesGetData)(sb, count); };

static struct oidfed_signature_algorithm (*OIFFn_oidfedSignatureAlgorithmCreateEmpty)() = 0;
struct oidfed_signature_algorithm OIFMayLoad_oidfedSignatureAlgorithmCreateEmpty_request(request_rec* wrap_request_ctx) { OIDFED_MAYLOAD_REQUEST(return, oidfedSignatureAlgorithmCreateEmpty)(); }
struct oidfed_signature_algorithm OIFMayLoad_oidfedSignatureAlgorithmCreateEmpty_server(server_rec* wrap_server_ctx) { OIDFED_MAYLOAD_SERVER(return, oidfedSignatureAlgorithmCreateEmpty)(); };

static void (*OIFFn_oidfedSignatureAlgorithmDestroy)(struct oidfed_signature_algorithm* sa) = 0;
void OIFMayLoad_oidfedSignatureAlgorithmDestroy_request(request_rec* wrap_request_ctx, struct oidfed_signature_algorithm* sa) { OIDFED_MAYLOAD_REQUEST(, oidfedSignatureAlgorithmDestroy)(sa); }
void OIFMayLoad_oidfedSignatureAlgorithmDestroy_server(server_rec* wrap_server_ctx, struct oidfed_signature_algorithm* sa) { OIDFED_MAYLOAD_SERVER(, oidfedSignatureAlgorithmDestroy)(sa); };

static struct oidfed_signature_algorithm (*OIFFn_oidfedSignatureAlgorithmGet)(char* name, _Bool* succ) = 0;
struct oidfed_signature_algorithm OIFMayLoad_oidfedSignatureAlgorithmGet_request(request_rec* wrap_request_ctx, char* name, _Bool* succ) { OIDFED_MAYLOAD_REQUEST(return, oidfedSignatureAlgorithmGet)(name, succ); }
struct oidfed_signature_algorithm OIFMayLoad_oidfedSignatureAlgorithmGet_server(server_rec* wrap_server_ctx, char* name, _Bool* succ) { OIDFED_MAYLOAD_SERVER(return, oidfedSignatureAlgorithmGet)(name, succ); };

static struct oidfed_signer (*OIFFn_oidfedSignerCreateFromPEM)(char* pemBytes, size_t pemCount, int* errc) = 0;
struct oidfed_signer OIFMayLoad_oidfedSignerCreateFromPEM_request(request_rec* wrap_request_ctx, char* pemBytes, size_t pemCount, int* errc) { OIDFED_MAYLOAD_REQUEST(return, oidfedSignerCreateFromPEM)(pemBytes, pemCount, errc); }
struct oidfed_signer OIFMayLoad_oidfedSignerCreateFromPEM_server(server_rec* wrap_server_ctx, char* pemBytes, size_t pemCount, int* errc) { OIDFED_MAYLOAD_SERVER(return, oidfedSignerCreateFromPEM)(pemBytes, pemCount, errc); };

static void (*OIFFn_oidfedSignerDestroy)(struct oidfed_signer* s) = 0;
void OIFMayLoad_oidfedSignerDestroy_request(request_rec* wrap_request_ctx, struct oidfed_signer* s) { OIDFED_MAYLOAD_REQUEST(, oidfedSignerDestroy)(s); }
void OIFMayLoad_oidfedSignerDestroy_server(server_rec* wrap_server_ctx, struct oidfed_signer* s) { OIDFED_MAYLOAD_SERVER(, oidfedSignerDestroy)(s); };

static struct oidfed_single_key_storage (*OIFFn_oidfedSingleKeyStorageCreate)(struct oidfed_signer signer, struct oidfed_signature_algorithm alg) = 0;
struct oidfed_single_key_storage OIFMayLoad_oidfedSingleKeyStorageCreate_request(request_rec* wrap_request_ctx, struct oidfed_signer signer, struct oidfed_signature_algorithm alg) { OIDFED_MAYLOAD_REQUEST(return, oidfedSingleKeyStorageCreate)(signer, alg); }
struct oidfed_single_key_storage OIFMayLoad_oidfedSingleKeyStorageCreate_server(server_rec* wrap_server_ctx, struct oidfed_signer signer, struct oidfed_signature_algorithm alg) { OIDFED_MAYLOAD_SERVER(return, oidfedSingleKeyStorageCreate)(signer, alg); };

static void (*OIFFn_oidfedSingleKeyStorageDestroy)(struct oidfed_single_key_storage* sks) = 0;
void OIFMayLoad_oidfedSingleKeyStorageDestroy_request(request_rec* wrap_request_ctx, struct oidfed_single_key_storage* sks) { OIDFED_MAYLOAD_REQUEST(, oidfedSingleKeyStorageDestroy)(sks); }
void OIFMayLoad_oidfedSingleKeyStorageDestroy_server(server_rec* wrap_server_ctx, struct oidfed_single_key_storage* sks) { OIDFED_MAYLOAD_SERVER(, oidfedSingleKeyStorageDestroy)(sks); };

static void (*OIFFn_oidfedTrustAnchorDestroy)(struct oidfed_trust_anchor* ta) = 0;
void OIFMayLoad_oidfedTrustAnchorDestroy_request(request_rec* wrap_request_ctx, struct oidfed_trust_anchor* ta) { OIDFED_MAYLOAD_REQUEST(, oidfedTrustAnchorDestroy)(ta); }
void OIFMayLoad_oidfedTrustAnchorDestroy_server(server_rec* wrap_server_ctx, struct oidfed_trust_anchor* ta) { OIDFED_MAYLOAD_SERVER(, oidfedTrustAnchorDestroy)(ta); };

static struct oidfed_trust_anchor (*OIFFn_oidfedTrustAnchorCreate)(char* id) = 0;
struct oidfed_trust_anchor OIFMayLoad_oidfedTrustAnchorCreate_request(request_rec* wrap_request_ctx, char* id) { OIDFED_MAYLOAD_REQUEST(return, oidfedTrustAnchorCreate)(id); }
struct oidfed_trust_anchor OIFMayLoad_oidfedTrustAnchorCreate_server(server_rec* wrap_server_ctx, char* id) { OIDFED_MAYLOAD_SERVER(return, oidfedTrustAnchorCreate)(id); };

static struct oidfed_trust_mark (*OIFFn_oidfedTrustMarkCreate)() = 0;
struct oidfed_trust_mark OIFMayLoad_oidfedTrustMarkCreate_request(request_rec* wrap_request_ctx) { OIDFED_MAYLOAD_REQUEST(return, oidfedTrustMarkCreate)(); }
struct oidfed_trust_mark OIFMayLoad_oidfedTrustMarkCreate_server(server_rec* wrap_server_ctx) { OIDFED_MAYLOAD_SERVER(return, oidfedTrustMarkCreate)(); };

static void (*OIFFn_oidfedTrustMarkSetType)(struct oidfed_trust_mark tm, char* typ) = 0;
void OIFMayLoad_oidfedTrustMarkSetType_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm, char* typ) { OIDFED_MAYLOAD_REQUEST(, oidfedTrustMarkSetType)(tm, typ); }
void OIFMayLoad_oidfedTrustMarkSetType_server(server_rec* wrap_server_ctx, struct oidfed_trust_mark tm, char* typ) { OIDFED_MAYLOAD_SERVER(, oidfedTrustMarkSetType)(tm, typ); };

static char* (*OIFFn_oidfedTrustMarkGetType)(struct oidfed_trust_mark tm) = 0;
char* OIFMayLoad_oidfedTrustMarkGetType_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm) { OIDFED_MAYLOAD_REQUEST(return, oidfedTrustMarkGetType)(tm); }
char* OIFMayLoad_oidfedTrustMarkGetType_server(server_rec* wrap_server_ctx, struct oidfed_trust_mark tm) { OIDFED_MAYLOAD_SERVER(return, oidfedTrustMarkGetType)(tm); };

static void (*OIFFn_oidfedTrustMarkSetIssuer)(struct oidfed_trust_mark tm, char* issuer) = 0;
void OIFMayLoad_oidfedTrustMarkSetIssuer_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm, char* issuer) { OIDFED_MAYLOAD_REQUEST(, oidfedTrustMarkSetIssuer)(tm, issuer); }
void OIFMayLoad_oidfedTrustMarkSetIssuer_server(server_rec* wrap_server_ctx, struct oidfed_trust_mark tm, char* issuer) { OIDFED_MAYLOAD_SERVER(, oidfedTrustMarkSetIssuer)(tm, issuer); };

static char* (*OIFFn_oidfedTrustMarkGetIssuer)(struct oidfed_trust_mark tm) = 0;
char* OIFMayLoad_oidfedTrustMarkGetIssuer_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm) { OIDFED_MAYLOAD_REQUEST(return, oidfedTrustMarkGetIssuer)(tm); }
char* OIFMayLoad_oidfedTrustMarkGetIssuer_server(server_rec* wrap_server_ctx, struct oidfed_trust_mark tm) { OIDFED_MAYLOAD_SERVER(return, oidfedTrustMarkGetIssuer)(tm); };

static void (*OIFFn_oidfedTrustMarkSetSelfIssued)(struct oidfed_trust_mark tm, _Bool selfIssued) = 0;
void OIFMayLoad_oidfedTrustMarkSetSelfIssued_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm, _Bool selfIssued) { OIDFED_MAYLOAD_REQUEST(, oidfedTrustMarkSetSelfIssued)(tm, selfIssued); }
void OIFMayLoad_oidfedTrustMarkSetSelfIssued_server(server_rec* wrap_server_ctx, struct oidfed_trust_mark tm, _Bool selfIssued) { OIDFED_MAYLOAD_SERVER(, oidfedTrustMarkSetSelfIssued)(tm, selfIssued); };

static _Bool (*OIFFn_oidfedTrustMarkIsSelfIssued)(struct oidfed_trust_mark tm) = 0;
_Bool OIFMayLoad_oidfedTrustMarkIsSelfIssued_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm) { OIDFED_MAYLOAD_REQUEST(return, oidfedTrustMarkIsSelfIssued)(tm); }
_Bool OIFMayLoad_oidfedTrustMarkIsSelfIssued_server(server_rec* wrap_server_ctx, struct oidfed_trust_mark tm) { OIDFED_MAYLOAD_SERVER(return, oidfedTrustMarkIsSelfIssued)(tm); };

static void (*OIFFn_oidfedTrustMarkSetJwt)(struct oidfed_trust_mark tm, char* jwt) = 0;
void OIFMayLoad_oidfedTrustMarkSetJwt_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm, char* jwt) { OIDFED_MAYLOAD_REQUEST(, oidfedTrustMarkSetJwt)(tm, jwt); }
void OIFMayLoad_oidfedTrustMarkSetJwt_server(server_rec* wrap_server_ctx, struct oidfed_trust_mark tm, char* jwt) { OIDFED_MAYLOAD_SERVER(, oidfedTrustMarkSetJwt)(tm, jwt); };

static char* (*OIFFn_oidfedTrustMarkGetJwt)(struct oidfed_trust_mark tm) = 0;
char* OIFMayLoad_oidfedTrustMarkGetJwt_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm) { OIDFED_MAYLOAD_REQUEST(return, oidfedTrustMarkGetJwt)(tm); }
char* OIFMayLoad_oidfedTrustMarkGetJwt_server(server_rec* wrap_server_ctx, struct oidfed_trust_mark tm) { OIDFED_MAYLOAD_SERVER(return, oidfedTrustMarkGetJwt)(tm); };

static void (*OIFFn_oidfedTrustMarkSetRefresh)(struct oidfed_trust_mark tm, _Bool refresh) = 0;
void OIFMayLoad_oidfedTrustMarkSetRefresh_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm, _Bool refresh) { OIDFED_MAYLOAD_REQUEST(, oidfedTrustMarkSetRefresh)(tm, refresh); }
void OIFMayLoad_oidfedTrustMarkSetRefresh_server(server_rec* wrap_server_ctx, struct oidfed_trust_mark tm, _Bool refresh) { OIDFED_MAYLOAD_SERVER(, oidfedTrustMarkSetRefresh)(tm, refresh); };

static _Bool (*OIFFn_oidfedTrustMarkIsRefresh)(struct oidfed_trust_mark tm) = 0;
_Bool OIFMayLoad_oidfedTrustMarkIsRefresh_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm) { OIDFED_MAYLOAD_REQUEST(return, oidfedTrustMarkIsRefresh)(tm); }
_Bool OIFMayLoad_oidfedTrustMarkIsRefresh_server(server_rec* wrap_server_ctx, struct oidfed_trust_mark tm) { OIDFED_MAYLOAD_SERVER(return, oidfedTrustMarkIsRefresh)(tm); };

static void (*OIFFn_oidfedTrustMarkSetMinLifetimeSeconds)(struct oidfed_trust_mark tm, uint64_t minLifetime) = 0;
void OIFMayLoad_oidfedTrustMarkSetMinLifetimeSeconds_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm, uint64_t minLifetime) { OIDFED_MAYLOAD_REQUEST(, oidfedTrustMarkSetMinLifetimeSeconds)(tm, minLifetime); }
void OIFMayLoad_oidfedTrustMarkSetMinLifetimeSeconds_server(server_rec* wrap_server_ctx, struct oidfed_trust_mark tm, uint64_t minLifetime) { OIDFED_MAYLOAD_SERVER(, oidfedTrustMarkSetMinLifetimeSeconds)(tm, minLifetime); };

static uint64_t (*OIFFn_oidfedTrustMarkGetMinLifetimeSeconds)(struct oidfed_trust_mark tm) = 0;
uint64_t OIFMayLoad_oidfedTrustMarkGetMinLifetimeSeconds_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm) { OIDFED_MAYLOAD_REQUEST(return, oidfedTrustMarkGetMinLifetimeSeconds)(tm); }
uint64_t OIFMayLoad_oidfedTrustMarkGetMinLifetimeSeconds_server(server_rec* wrap_server_ctx, struct oidfed_trust_mark tm) { OIDFED_MAYLOAD_SERVER(return, oidfedTrustMarkGetMinLifetimeSeconds)(tm); };

static void (*OIFFn_oidfedTrustMarkSetRefreshGracePeriod)(struct oidfed_trust_mark tm, uint64_t refreshGracePeriod) = 0;
void OIFMayLoad_oidfedTrustMarkSetRefreshGracePeriod_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm, uint64_t refreshGracePeriod) { OIDFED_MAYLOAD_REQUEST(, oidfedTrustMarkSetRefreshGracePeriod)(tm, refreshGracePeriod); }
void OIFMayLoad_oidfedTrustMarkSetRefreshGracePeriod_server(server_rec* wrap_server_ctx, struct oidfed_trust_mark tm, uint64_t refreshGracePeriod) { OIDFED_MAYLOAD_SERVER(, oidfedTrustMarkSetRefreshGracePeriod)(tm, refreshGracePeriod); };

static uint64_t (*OIFFn_oidfedTrustMarkGetRefreshGracePeriod)(struct oidfed_trust_mark tm) = 0;
uint64_t OIFMayLoad_oidfedTrustMarkGetRefreshGracePeriod_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark tm) { OIDFED_MAYLOAD_REQUEST(return, oidfedTrustMarkGetRefreshGracePeriod)(tm); }
uint64_t OIFMayLoad_oidfedTrustMarkGetRefreshGracePeriod_server(server_rec* wrap_server_ctx, struct oidfed_trust_mark tm) { OIDFED_MAYLOAD_SERVER(return, oidfedTrustMarkGetRefreshGracePeriod)(tm); };

static void (*OIFFn_oidfedTrustMarkDestroy)(struct oidfed_trust_mark* tm) = 0;
void OIFMayLoad_oidfedTrustMarkDestroy_request(request_rec* wrap_request_ctx, struct oidfed_trust_mark* tm) { OIDFED_MAYLOAD_REQUEST(, oidfedTrustMarkDestroy)(tm); }
void OIFMayLoad_oidfedTrustMarkDestroy_server(server_rec* wrap_server_ctx, struct oidfed_trust_mark* tm) { OIDFED_MAYLOAD_SERVER(, oidfedTrustMarkDestroy)(tm); };

static struct oidfed_trust_resolver (*OIFFn_oidfedTrustResolverCreate)(char* subID, struct oidfed_trust_anchor* anchors, size_t anchorsCount) = 0;
struct oidfed_trust_resolver OIFMayLoad_oidfedTrustResolverCreate_request(request_rec* wrap_request_ctx, char* subID, struct oidfed_trust_anchor* anchors, size_t anchorsCount) { OIDFED_MAYLOAD_REQUEST(return, oidfedTrustResolverCreate)(subID, anchors, anchorsCount); }
struct oidfed_trust_resolver OIFMayLoad_oidfedTrustResolverCreate_server(server_rec* wrap_server_ctx, char* subID, struct oidfed_trust_anchor* anchors, size_t anchorsCount) { OIDFED_MAYLOAD_SERVER(return, oidfedTrustResolverCreate)(subID, anchors, anchorsCount); };

static void (*OIFFn_oidfedTrustResolverDestroy)(struct oidfed_trust_resolver* r) = 0;
void OIFMayLoad_oidfedTrustResolverDestroy_request(request_rec* wrap_request_ctx, struct oidfed_trust_resolver* r) { OIDFED_MAYLOAD_REQUEST(, oidfedTrustResolverDestroy)(r); }
void OIFMayLoad_oidfedTrustResolverDestroy_server(server_rec* wrap_server_ctx, struct oidfed_trust_resolver* r) { OIDFED_MAYLOAD_SERVER(, oidfedTrustResolverDestroy)(r); };

static struct oidfed_trust_chains (*OIFFn_oidfedTrustResolverResolveToValidChains)(struct oidfed_trust_resolver r) = 0;
struct oidfed_trust_chains OIFMayLoad_oidfedTrustResolverResolveToValidChains_request(request_rec* wrap_request_ctx, struct oidfed_trust_resolver r) { OIDFED_MAYLOAD_REQUEST(return, oidfedTrustResolverResolveToValidChains)(r); }
struct oidfed_trust_chains OIFMayLoad_oidfedTrustResolverResolveToValidChains_server(server_rec* wrap_server_ctx, struct oidfed_trust_resolver r) { OIDFED_MAYLOAD_SERVER(return, oidfedTrustResolverResolveToValidChains)(r); };

static size_t (*OIFFn_oidfedTrustChainsCount)(struct oidfed_trust_chains chains) = 0;
size_t OIFMayLoad_oidfedTrustChainsCount_request(request_rec* wrap_request_ctx, struct oidfed_trust_chains chains) { OIDFED_MAYLOAD_REQUEST(return, oidfedTrustChainsCount)(chains); }
size_t OIFMayLoad_oidfedTrustChainsCount_server(server_rec* wrap_server_ctx, struct oidfed_trust_chains chains) { OIDFED_MAYLOAD_SERVER(return, oidfedTrustChainsCount)(chains); };

static struct oidfed_trust_chain (*OIFFn_oidfedTrustChainsGet)(struct oidfed_trust_chains chains, size_t index) = 0;
struct oidfed_trust_chain OIFMayLoad_oidfedTrustChainsGet_request(request_rec* wrap_request_ctx, struct oidfed_trust_chains chains, size_t index) { OIDFED_MAYLOAD_REQUEST(return, oidfedTrustChainsGet)(chains, index); }
struct oidfed_trust_chain OIFMayLoad_oidfedTrustChainsGet_server(server_rec* wrap_server_ctx, struct oidfed_trust_chains chains, size_t index) { OIDFED_MAYLOAD_SERVER(return, oidfedTrustChainsGet)(chains, index); };

static void (*OIFFn_oidfedTrustChainsDestroy)(struct oidfed_trust_chains* chains) = 0;
void OIFMayLoad_oidfedTrustChainsDestroy_request(request_rec* wrap_request_ctx, struct oidfed_trust_chains* chains) { OIDFED_MAYLOAD_REQUEST(, oidfedTrustChainsDestroy)(chains); }
void OIFMayLoad_oidfedTrustChainsDestroy_server(server_rec* wrap_server_ctx, struct oidfed_trust_chains* chains) { OIDFED_MAYLOAD_SERVER(, oidfedTrustChainsDestroy)(chains); };

static void (*OIFFn_oidfedTrustChainDestroy)(struct oidfed_trust_chain* chain) = 0;
void OIFMayLoad_oidfedTrustChainDestroy_request(request_rec* wrap_request_ctx, struct oidfed_trust_chain* chain) { OIDFED_MAYLOAD_REQUEST(, oidfedTrustChainDestroy)(chain); }
void OIFMayLoad_oidfedTrustChainDestroy_server(server_rec* wrap_server_ctx, struct oidfed_trust_chain* chain) { OIDFED_MAYLOAD_SERVER(, oidfedTrustChainDestroy)(chain); };

static struct oidfed_metadata (*OIFFn_oidfedTrustChainGetMetadata)(struct oidfed_trust_chain chain, int* errc) = 0;
struct oidfed_metadata OIFMayLoad_oidfedTrustChainGetMetadata_request(request_rec* wrap_request_ctx, struct oidfed_trust_chain chain, int* errc) { OIDFED_MAYLOAD_REQUEST(return, oidfedTrustChainGetMetadata)(chain, errc); }
struct oidfed_metadata OIFMayLoad_oidfedTrustChainGetMetadata_server(server_rec* wrap_server_ctx, struct oidfed_trust_chain chain, int* errc) { OIDFED_MAYLOAD_SERVER(return, oidfedTrustChainGetMetadata)(chain, errc); };

static void (*OIFFn_oidfedMetadataDestroy)(struct oidfed_metadata* m) = 0;
void OIFMayLoad_oidfedMetadataDestroy_request(request_rec* wrap_request_ctx, struct oidfed_metadata* m) { OIDFED_MAYLOAD_REQUEST(, oidfedMetadataDestroy)(m); }
void OIFMayLoad_oidfedMetadataDestroy_server(server_rec* wrap_server_ctx, struct oidfed_metadata* m) { OIDFED_MAYLOAD_SERVER(, oidfedMetadataDestroy)(m); };

static void (*OIFFn_oidfedUiInfoDestroy)(struct oidfed_ui_info* ui) = 0;
void OIFMayLoad_oidfedUiInfoDestroy_request(request_rec* wrap_request_ctx, struct oidfed_ui_info* ui) { OIDFED_MAYLOAD_REQUEST(, oidfedUiInfoDestroy)(ui); }
void OIFMayLoad_oidfedUiInfoDestroy_server(server_rec* wrap_server_ctx, struct oidfed_ui_info* ui) { OIDFED_MAYLOAD_SERVER(, oidfedUiInfoDestroy)(ui); };

